#!/bin/bash
## Main Parser


case "$1" in

boot)
## Mount Flash Drive
mkdir -p /home/pi/RetroPie
mount /dev/sda1 /home/pi/RetroPie
## Turn on Swap File
sleep 2.5
swapon /home/pi/RetroPie/swapfile
## Start Hotspot
#sleep 60
#/bin/bash /etc/netmode.sh apd > /dev/null 2>&1
exit
;;

usbplug)
## This script is ran after USB drive attached and when its removed.
echo "no function assigned"
exit
;;
    
*)
  exit 1
;;
esac   
