#!/bin/bash
## Main Parser


case "$1" in

boot)
## Turn on Swap File
mkdir -p /home/pi
mount /dev/sda1 /home/pi
sleep 2.5
swapon /home/pi/swapfile
exit
;;

usbplug)
echo "no function assigned"
exit
;;
    
*)
  exit 1
;;
esac   
