#!/bin/bash
###########################################################
## LEDstrips main script by Ben Provenzano III ##############
###########################################################
###########################################################

case "$1" in

boot)
/opt/rpi/leds fc norm
## Auto Hotspot (on boot only)
systemctl restart rpi-netdetect
## Turn off power LED
echo 0 > /sys/class/leds/ACT/brightness
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

	    
    *)
        if [ "$1" == "" ]; then
          echo "Enter valid command."
        else  
	      if [ "$2" == "" ]; then
	        echo "Sending $1 command..."
	      else
	      	echo "Sending $1:$2 command..."
	      fi  
	      /opt/rpi/leds "$1" "$2" 
	    fi
      exit
      ;;
    esac
