#!/bin/bash
###########################################################
## LEDstrips main script by Ben Provenzano III ##############
###########################################################
###########################################################

case "$1" in

boot)
/opt/rpi/leds fc norm
## Auto Hotspot (on boot only)
systemctl restart rpi-netdetect
## Disable HDMI (saves 30mA)
/usr/bin/tvservice -o
exit
;;

lcdon)
## LCD on
sudo sh -c 'echo 0 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdoff)
## LCD off
sudo sh -c 'echo 1 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdstd)
## Standard LCD Brightness
sudo sh -c 'echo "110" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcdlow)
## Low LCD Brightness
sudo sh -c 'echo "50" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd50)
## 50% LCD Brightness
sudo sh -c 'echo "100" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd75)
## 75% LCD Brightness
sudo sh -c 'echo "170" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd100)
## Full LCD Brightness
sudo sh -c 'echo "255" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

	    
    *)
        if [ "$1" == "" ]; then
          echo "Enter valid command."
        else  
	      if [ "$2" == "" ]; then
	        echo "Sending $1 command..."
	      else
	      	echo "Sending $1:$2 command..."
	      fi  
	      /usr/bin/curl --silent --fail --ipv4 --no-buffer --max-time 30 \
	      --retry 3 --retry-all-errors --retry-delay 1 --no-keepalive \
	      --data "var=$2&arg=$1&action=leds" http://127.0.0.1/exec.php
	    fi
      exit 1
      ;;
    esac
