#!/bin/sh
## LEDwall Configuration Script v7.0

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
## Set Bridge Mode Flag
touch /boot/ap-bridge.enable
## Disable Auto Hotspot
touch /boot/autohotspot.off
########################
mount -o remount,ro /boot

## Set LED Type
rm -f /opt/rpi/ledtype.txt
echo "93ring" > /opt/rpi/ledtype.txt

## Shortcut to main script
ln -sf /opt/rpi/main /usr/bin/leds

## Replacement LED modules (for 93-pixel LED ring)
cp -f $BIN/modconf/SpectroGraph.jar /opt/rpi/effects/spectro/lib/
chmod 755 /opt/rpi/effects/spectro/lib/SpectroGraph.jar
chown root:root /opt/rpi/effects/spectro/lib/SpectroGraph.jar

## Routed Hotspot Configuration
#cp -f /etc/dnsmasq.routed /etc/dnsmasq.conf
#chmod 644 /etc/dnsmasq.conf
#chown root:root /etc/dnsmasq.conf

exit
