#!/bin/sh
## LEDwall Configuration Script

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e "/opt/rpi/init" ]; then
  echo "Core components missing or corrupted."
  echo "Exiting..."
  exit
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
touch /boot/firmware/autohotspot.off ## Disable Auto Hotspot
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Set LED Type
rm -f /opt/rpi/ledtype.txt
echo "93ring" > /opt/rpi/ledtype.txt

## Web Interface
cp -v /opt/rpi/device.js /var/www/html/
chmod -R 777 /var/www/html/device.js
chown -R www-data:www-data /var/www/html/device.js

## Shortcut to main script
ln -sf /opt/rpi/leds /usr/bin/leds

## Replacement LED modules (for 93-pixel LED ring)
cp -f $BIN/modconf/SpectroGraph.jar /opt/rpi/effects/spectro/lib/
chmod 755 /opt/rpi/effects/spectro/lib/SpectroGraph.jar
chown root:root /opt/rpi/effects/spectro/lib/SpectroGraph.jar

exit
