#!/bin/bash

## Cameras Cleanup Script for Pi
### run as root user only!

CAMERA1="Driveway"
CAMERA2="Porch"

## Remove Motion Restart Log History
truncate -s 0 /tmp/motionping.log

## Check if Google Drive connected before cleanup
if [ ! -e /mnt/gsync/Current ]; then
  echo "Google Drive not connected."
else
  echo "Google Drive connected."
  ## Delete archived videos, when larger than 14GB
  rm -f /tmp/camcleanup.vars
  du -sh -t14000000000 /mnt/gsync | awk -F" " '{print $2}' > /tmp/camcleanup.vars
  if [[ -s /tmp/camcleanup.vars ]] ; then
	echo "Google Drive above 14GB limit deleting archived video files..."
	service motion stop
  rm -rf /mnt/gsync/Archive/$CAMERA1
  mkdir -p /mnt/gsync/Archive/$CAMERA1
  chmod -R 777 /mnt/gsync/Archive/$CAMERA1
  rm -rf /mnt/gsync/Archive/$CAMERA2
  mkdir -p /mnt/gsync/Archive/$CAMERA2
  chmod -R 777 /mnt/gsync/Archive/$CAMERA2 
	service motion start
  else
    echo "Google Drive under 14GB."
  fi
  rm -f /tmp/camcleanup.vars
  ## Move videos to archive when Google Drive is larger than 6GB
  rm -f /tmp/camcleanup.vars
  du -sh -t6000000000 /mnt/gsync/Current | awk -F" " '{print $2}' > /tmp/camcleanup.vars
  if [[ -s /tmp/camcleanup.vars ]] ; then
	echo "Google Drive current folder above 6GB limit moving video files..."
	service motion stop
  mkdir -p /mnt/gsync/Archive
  mkdir -p /mnt/gsync/Archive/$CAMERA1
  mv /mnt/gsync/Current/$CAMERA1/* /mnt/gsync/Archive/$CAMERA1/
  mkdir -p /mnt/gsync/Archive/$CAMERA2
  mv /mnt/gsync/Current/$CAMERA2/* /mnt/gsync/Archive/$CAMERA2/
	service motion start
  else
    echo "Google Drive current folder under 6GB."
  fi
  rm -f /tmp/camcleanup.vars
fi

## Check if flash drive is connected before cleanup
if [ ! -e /media/usb0/cameras ]; then
  echo "Flash drive not connected."
else
  echo "Flash drive connected."
  ## Delete videos, when larger than 15GB
  rm -f /tmp/camcleanup.vars
  du -sh -t15000000000 /media/usb0/cameras | awk -F" " '{print $2}' > /tmp/camcleanup.vars
  if [[ -s /tmp/camcleanup.vars ]] ; then
	echo "Flash drive above 15GB limit deleting video files..."
	service motion stop
  rm -rf /media/usb0/cameras/$CAMERA1
  mkdir -p /media/usb0/cameras/$CAMERA1
  chmod -R 777 /media/usb0/cameras/$CAMERA1
  rm -rf /media/usb0/cameras/$CAMERA2
  mkdir -p /media/usb0/cameras/$CAMERA2
  chmod -R 777 /media/usb0/cameras/$CAMERA2 
	service motion start
  else
    echo "Flash drive under 15GB."
  fi
  rm -f /tmp/camcleanup.vars
fi

exit