#!/bin/bash
###########################################################
####### Motion copy script by Ben Provenzano III v1 #######
###########################################################

## Read camera name
VARA=$1
## Read file name
VARB=$2

## Test file names
#touch /tmp/motioncam.log
#echo "$VARA" | tee -a /tmp/motioncam.log
#touch /tmp/motionfile.log
#echo "$VARB" | tee -a /tmp/motionfile.log

## Copy video to Google Drive
if [ ! -e /mnt/gsync/Current ]; then
  echo "Google Drive not connected."
  if [ ! -e /media/usb0/cameras ]; then
    echo "Flash drive not connected."
  else
    mkdir -p /media/usb0/cameras/$VARA
    cp -f $VARB.mp4 /media/usb0/cameras/$VARA/
  fi
else
  mkdir -p /mnt/gsync/Current/$VARA
  cp -f $VARB.mp4 /mnt/gsync/Current/$VARA/
fi

## Delete video from RAM Disk
rm -f $VARB.mp4

exit