#!/bin/bash
###########################################################
####### Motion copy script by Ben Provenzano III v1 #######
###########################################################

## Read Camera Name
VARA=$1
## Read File Name
VARB=$2

## Test File Names
#touch /tmp/motioncam.log
#echo "$VARA" | tee -a /tmp/motioncam.log
#touch /tmp/motionfile.log
#echo "$VARB" | tee -a /tmp/motionfile.log

## Copy Video to Google Drive
if [ ! -e /mnt/gsync/Current ]; then
   echo "Google Drive not connected."
else
   mkdir -p /mnt/gsync/Current/$VARA
   cp -f $VARB.mp4 /mnt/gsync/Current/$VARA/
fi

## Copy video to Flash drive if Server & Google Drive not connected 
if [ ! -e /mnt/smb/Cameras/Current ]; then
  if [ ! -e /mnt/gsync/Current ]; then
    if [ ! -e /media/usb0/cameras ]; then
      echo "Flash drive not connected."
    else
      mkdir -p /media/usb0/cameras/$VARA
      cp -f $VARB.mp4 /media/usb0/cameras/$VARA/
    fi
  fi
else
  mkdir -p /mnt/smb/Cameras/Current/$VARA
  cp -f $VARB.mp4 /mnt/smb/Cameras/Current/$VARA/
fi

## Delete Original from RAM Disk
rm -f $VARB.mp4

exit