#!/bin/bash
###########################################################

## Arduino's Serial Port
ARDUINO_PORT="ttyUSB0"

## Read Command-Line Arguments
ARG1="${1}"
ARG2="${2}"

BLINKLED() {
  ## Blink front-panel LED
  nohup python3 /opt/rpi/blinkled.py >/dev/null 2>&1 &
}

ZTERM_COM() {
  local CMD_DATA="${1}"
  /opt/rpi/singleton.sh ZTERM_PROC /usr/bin/ztermcom $CMD_DATA
}

OPTA_MODE() {
  ## Optical A: input
  ZTERM_COM "02002"
}

OPTB_MODE() {
  ## Optical B: input
  ZTERM_COM "02001" 
}

COAX_MODE() {
  ## Coaxial input
  ZTERM_COM "02003" 
}

function DECODE_COM_RESP(){
  ## read character position
  local RESP_CMD="${1}"
  TTY_RAW="$(ZTERM_COM $RESP_CMD)"
  ## extract response data
  DELIM="|"
  TMP_STR="${TTY_RAW#*$DELIM}"
  TTY_OUT="${TMP_STR%$DELIM*}"
  ## process by response length
  TTY_CHR_CNT="${#TTY_OUT}"
  case "$TTY_CHR_CNT" in
  ## single-byte response
  "1")
    TTY_CHR="${TTY_OUT:0:1}"
    echo "$TTY_CHR"
    ;;
  ## 
  *)
    ## invalid response
    echo "X"
    ;;
  esac
}

case "$ARG1" in

boot)
## Start amplifier communication
ln -sf /dev/$ARDUINO_PORT /dev/zterm-tty
ZTERM_COM i
## Bluetooth audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## AirPlay Support
systemctl start rpi-airplay
BLINKLED
## SMB file share client
systemctl start autofs
exit
;;

serialmon)
/opt/rpi/arduino-cli monitor -p /dev/$ARDUINO_PORT -b arduino:avr:uno --config 9600
exit
;;

relax)
## turn on amp and set input
if  [ "$(DECODE_COM_RESP '01005')" == "1" ]; then
  ## amp is online (set to coax input)
  COAX_MODE
else
  ## amp if offline (power on then set to coax input)
  ZTERM_COM "01003"
fi
systemctl stop rpi-relaxloop
systemctl set-environment rpi_relaxmode="$ARG2"
systemctl start rpi-relaxloop
BLINKLED
exit
;;

stoprelax)
OPTA_MODE
systemctl stop rpi-relaxloop
BLINKLED
exit
;;

opt-a)
OPTA_MODE
BLINKLED
exit
;;

opt-b)
OPTB_MODE
BLINKLED
exit
;;

coaxial)
COAX_MODE
BLINKLED
exit
;;

aux)
ZTERM_COM "02004"
BLINKLED
exit
;;

volup)
ZTERM_COM "03002"
BLINKLED
exit
;;

voldwn)
ZTERM_COM "03003"
BLINKLED
exit
;;

volmute)
ZTERM_COM "03001" 
BLINKLED
exit
;;

ampon-lastin)
## Power On to Last Input
ZTERM_COM "01001"
BLINKLED
exit
;;

ampstateon)
## Power On to Optical #B Input
ZTERM_COM "01004"
BLINKLED
exit
;;

ampstateoff)
## Power Off
ZTERM_COM "01002"
systemctl stop rpi-relaxloop
BLINKLED
exit
;;

amptogglepwr)
## Toggle Power
if  [ "$(DECODE_COM_RESP '01005')" == "1" ]; then
  ## is online
  ZTERM_COM "01002" ## Power Off
else
  ## if offline
  ZTERM_COM "01001" ## Power On (Last Input)
fi
BLINKLED
exit
;;

ampstate)
## Power State
ZTERM_COM "01005"
exit
;;

inputstate)
## Input State
ZTERM_COM "01006"
exit
;;

volstate)
## Volume State
ZTERM_COM "01007"
exit
;;

update-fw)
BLINKLED
UNO_FRM="IntegratedAmp"
## Stop Serial Communication
rm -rfv /dev/zterm-tty
## Update Arduino over USB
rm -rf "/opt/rpi/$UNO_FRM/build"
mkdir -p "/opt/rpi/$UNO_FRM/build"
/opt/rpi/arduino-cli -v compile --fqbn arduino:avr:uno \
  "/opt/rpi/$UNO_FRM/$UNO_FRM.ino" --build-path "/opt/rpi/$UNO_FRM/build"
/opt/rpi/arduino-cli -v upload -p "/dev/$ARDUINO_PORT" \
  --fqbn arduino:avr:uno --input-dir "/opt/rpi/$UNO_FRM/build"
## Start amplifier communication
ln -sf "/dev/$ARDUINO_PORT" /dev/zterm-tty
ZTERM_COM "i"
exit
;;

*)
echo "Bedroom Pi - by Ben Provenzano III "
echo "Enter valid command."
exit 1
;;
esac   
