#!/bin/bash
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
OSVER="$(sed -n 's|^VERSION=".*(\(.*\))"|\1|p' /etc/os-release)"
if [ "${OSVER}" = "bookworm" ]; then
  mount -o remount,rw /boot/firmware
  cp -f $BIN/modconf/config.txt /boot/firmware/
  mount -o remount,ro /boot/firmware
else
  mount -o remount,rw /boot
  cp -f $BIN/modconf/config.txt /boot/
  mount -o remount,ro /boot
fi

## Terminal Service
cp -f $BIN/modconf/ztermcom.service /etc/systemd/system/
chmod -f 644 /etc/systemd/system/ztermcom.service
chown -f root:root /etc/systemd/system/ztermcom.service
rm -f /etc/systemd/system/ztermcom.socket
/usr/bin/gcc /opt/rpi/ztermcom.c -o /usr/bin/ztermcom
chmod +x /usr/bin/ztermcom 
chown root:root /usr/bin/ztermcom 
systemctl disable ztermcom.service
systemctl restart ztermcom.service

## Remove archived messages
rm -rfv /tmp/message*.txt

## Web Interface
cp -v /opt/rpi/device.js /var/www/html/
chmod -R 777 /var/www/html/device.js
chown -R www-data:www-data /var/www/html/device.js
cp -v /opt/rpi/upload.php /var/www/html/
chmod -R 777 /var/www/html/upload.php
chown -R www-data:www-data /var/www/html/upload.php

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

exit
