#!/bin/bash
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
mount -o remount,ro /boot

## Terminal Service
cp -f $BIN/modconf/ztermcom.service /etc/systemd/system/
chmod -f 644 /etc/systemd/system/ztermcom.service
chown -f root:root /etc/systemd/system/ztermcom.service
rm -f /etc/systemd/system/ztermcom.socket
/usr/bin/gcc /opt/rpi/ztermcom.c -o /usr/bin/ztermcom
chmod +x /usr/bin/ztermcom 
chown root:root /usr/bin/ztermcom 
systemctl disable ztermcom.service
systemctl restart ztermcom.service

## Web Interface
cp -rv $BIN/modconf/index.html /var/www/html/
chmod 777 /var/www/html/index.html
chown www-data:www-data /var/www/html/index.html

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

exit
