#!/bin/bash
###########################################################

case "$1" in

boot)
## Light Web Server
systemctl restart lighttpd
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
sleep 5
/opt/rpi/main resetbt
## AirPlay Support
#systemctl start rpi-airplay
## Disable Activity LED
echo none | tee /sys/class/leds/led0/trigger
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Auto Hotspot (on boot only)
sleep 60
systemctl start rpi-netdetect.service
exit
;;

resetbt)
## Reset Bluetooth Connections 
for device in $(bluetoothctl devices  | grep -o "[[:xdigit:]:]\{8,17\}"); do
    echo "removing bluetooth device: $device | $(bluetoothctl remove $device)"
done
exit
;;
	    
    *)
      echo "Bluetooth Audio Server for Raspberry Pi"
	    echo "  by Ben Provenzano III"
	    echo " "
	    echo "Enter a valid command line argument."
      echo "resetbt - Clear active bluetooth connections"
      exit 1
      ;;
    esac
