#!/bin/bash
###########################################################

case "$1" in

boot)
## State Folder
rm -rf /var/lock/rpi
mkdir -p /var/lock/rpi
chmod -R 777 /var/lock/rpi
## Light Web Server
systemctl restart lighttpd
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## Reset Bluetooth Connections
sleep 5
/opt/rpi/init resetbt
## Disable Activity LED
echo none | tee /sys/class/leds/led0/trigger
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Auto Hotspot (on boot only)
sleep 60 # only run if bluetooth not connected
if [ ! -e /tmp/bt.connected ]; then
   systemctl start rpi-netdetect.service
fi
exit
;;
	    
    *)
      echo "Bluetooth Audio Server for Raspberry Pi"
	  echo "  by Ben Provenzano III"
      exit 1
      ;;
    esac
