#!/bin/bash
###########################################################

## Read the 2nd Argument
ARG2=$2

## Read the 1st Argument
case "$1" in

boot)
## Startup Sound
/usr/bin/mpv --no-video --volume=40 /opt/rpi/sounds/ps2.wav &
## CPU Activity LED Mode
echo cpu | tee /sys/class/leds/led0/trigger &>/dev/null
## AirPlay Support
systemctl start nqptp
systemctl start rpi-airplay
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## Auto Hotspot (on boot only)
# only run if bluetooth not connected
if [ ! -e /tmp/bt.connected ]; then
  systemctl start rpi-netdetect.service
fi
## Disable HDMI (saves 30mA)
tvservice -o
exit
;;

relax)
## Play sound in loop
systemctl stop rpi-relaxloop
systemctl set-environment rpi_relaxmode=$ARG2
systemctl start rpi-relaxloop
exit
;;

stoprelax)
systemctl stop rpi-relaxloop
exit
;;



        *)
          echo "HiFi System"
	      echo "  by Ben Provenzano III "
          exit 1
          ;;
    esac   
