#!/bin/bash
###########################################################

## Read the 2nd Argument
ARG2=$2

## Read the 1st Argument
case "$1" in

boot)
## State Folder
rm -rf /var/lock/rpi
mkdir -p /var/lock/rpi
chmod -R 777 /var/lock/rpi
## Light Web Server
systemctl start lighttpd
## AirPlay Support
systemctl start rpi-airplay
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## Attach Server SMB Share
sleep 5.75
if ping -c 1 files.home > /dev/null 2> /dev/null
then
  systemctl start autofs
fi
## Auto Hotspot (on boot only)
sleep 60 # only run if bluetooth not connected
if [ ! -e /tmp/bt.connected ]; then
   systemctl start rpi-netdetect.service
fi
exit
;;

### Relaxation Sound Playback
stoprelax)
killall -s KILL -w omxplayer
exit
;;
##
relax)
killall -s KILL -w omxplayer
## Capitialize first letter of argument
ARG2="${ARG2^}"
## Play Audio in Loop
/usr/bin/omxplayer -o alsa --loop "/mnt/smb/Media/Sounds/Relaxation/$ARG2.mp3"
exit
;;


        *)
          echo "HiFi System"
	        echo "  by Ben Provenzano III "
          exit 1
          ;;
    esac   
