#!/bin/bash

## Cameras Cleanup Script for Pi
### run as root user only!

FLASH_PATH="/media/usb0"

## Log file path
if [ ! -e $FLASH_PATH/cameras ]; then
  LOGFILE="/tmp/camcleanup.log"
else
  LOGFILE="$FLASH_PATH/cameras/camcleanup.log"
fi  

## Check if Google Drive connected before cleanup
if ping -W 10 -c 1 8.8.8.8 > /dev/null 2> /dev/null
then
  echo "Google Drive connected."
  ## Move videos to archive when Google Drive is 50% full
  DISKCAP=""
  DISKCAP=$(timeout 500 df -Pk /mnt/gsync | awk 'NR==2 {print $5}')
  TM_STATUS=$?
  if [[ ("$TM_STATUS" -gt 100 ) || ("$TM_STATUS" -eq 1) ]]
  then
    echo "Timeout exceeded restarting rclone $(date)" >> $LOGFILE
    service motion stop
    service rpi-rclone restart
    service motion start   
  fi  
  DISKCAP=${DISKCAP%\%}
  if [[ "$DISKCAP" -gt "50" ]] ; then
	  echo "Google Drive usage $DISKCAP% moving videos to archive... $(date)" >> $LOGFILE
	  mkdir -p /mnt/gsync/Archive
      TIMESTAMP="$(date +%H-%m-%d)"
      mkdir -p /mnt/gsync/Archive/$TIMESTAMP
	  mv /mnt/gsync/Current/* /mnt/gsync/Archive/$TIMESTAMP/
  else
    echo "Google Drive usage less than 50% not moving to archive"
  fi
  ###############################################################
  ## Delete archived videos, when Google Drive is 95% full
  DISKCAP=""
  DISKCAP=$(timeout 500 df -Pk /mnt/gsync | awk 'NR==2 {print $5}')
  TM_STATUS=$?
  if [[ ("$TM_STATUS" -gt 100 ) || ("$TM_STATUS" -eq 1) ]]
  then
    echo "Timeout exceeded restarting rclone $(date)" >> $LOGFILE
    service motion stop
    service rpi-rclone restart
    service motion start   
  fi
  DISKCAP=${DISKCAP%\%}
  if [[ "$DISKCAP" -gt "95" ]] ; then
	  echo "Google Drive usage $DISKCAP% deleting archived video files $(date)" >> $LOGFILE
	  rm -rf /mnt/gsync/Archive
	  mkdir -p /mnt/gsync/Archive
	  chmod -R 777 /mnt/gsync/Archive
  else
    echo "Google Drive usage less than 95% not deleting archived"
  fi
else
  echo "Google ping exceeded 10 seconds, cleanup not ran $(date)" >> $LOGFILE
fi

## Check if flash drive is connected before cleanup
if [ ! -e $FLASH_PATH/cameras ]; then
  echo "Flash drive not connected."
else
  echo "Flash drive connected."
  truncate -s '<5MB' /media/usb0/cameras/motioncopy.log
  truncate -s '<5MB' /media/usb0/cameras/camcleanup.log
  ## Delete videos, when flash drive has only 2GB free
  DISKCAP=""
  DISKCAP=$(timeout 500 df -Pk /media/usb0 | awk 'NR==2 {print $5}')
  TM_STATUS=$?
  if [[ ("$TM_STATUS" -gt 100 ) || ("$TM_STATUS" -eq 1) ]]
  then
    echo "Timeout exceeded checking flash drive usage, exiting $(date)" >> $LOGFILE
    exit
  fi  
  DISKCAP=${DISKCAP%\%}
  if [[ "$DISKCAP" -gt "95" ]] ; then
	  echo "Flash drive usage $DISKCAP% deleting video files... $(date)" >> $LOGFILE
	  rm -rf $FLASH_PATH/cameras/*/*.mp4
	  chmod -R 777 $FLASH_PATH/cameras
  else
    echo "Flash drive under 95% usage"
  fi
fi

## Log file trim
truncate -s '<128KB' /tmp/motionping.log
truncate -s '<128KB' /tmp/motioncopy.log
truncate -s '<128KB' /tmp/camcleanup.log

exit