#!/bin/bash
####### RPi Cleanup by Ben Provenzano III #######
## This script runs 5hr after boot and every 12 hrs

## Cleanup Files
truncate -s 0 /var/log/lastlog
truncate -s 0 /var/log/wtmp
truncate -s 0 /var/log/btmp
truncate -s 0 /var/log/Xorg.0.log.old
truncate -s 0 /var/log/Xorg.0.log
truncate -s 0 /var/log/faillog
truncate -s 0 /root/.xsession-errors
truncate -s 0 /root/.bash_history
truncate -s 0 /home/pi/.xsession-errors
truncate -s 0 /home/pi/.bash_history
rm -rf /var/www/sessions/*

exit