#!/bin/bash
###########################################################
###### LED Effects Script by Ben Provenzano III v15 #######
###########################################################

## Read Input Arguments
VARA=$1
VARB=$2

## Main Path
BIN_PATH=/opt/rpi

## Stop LED processes
LEDSTOP(){
/usr/bin/curl --silent --output /dev/null -X POST http://127.0.0.1:9387/api/anim/stop
systemctl stop rpi-fcleds
echo "Paused effects"
}

## LEDsync Command Dispatcher (make sure .txt file has newline at end)
if [ -e $BIN_PATH/ledsync.txt ]; then
  LEDFILE='$BIN_PATH/ledsync.txt'
  exec 4<$LEDFILE
  while read -u4 PSYNC ; do
      echo "Sending $VARA command to $PSYNC LED server..."
      /usr/bin/screen -dm /usr/bin/curl -N -f -m 10 --silent --data \
       "var=$VARB&arg=$VARA&action=leds" http://$PSYNC:9300/exec.php
      sleep 0.25
  done
fi

## Read LED Type
if [ ! -e $BIN_PATH/ledtype.txt ]; then
  exit
fi
LEDTYPE=`cat $BIN_PATH/ledtype.txt`

## Pick a random effect
if [ "$VARA" = "shuffle" ]; then
  SHUF_IN=$BIN_PATH/effects/shuffle.txt
  SHUF_OUT=$(<$SHUF_IN sort | uniq | sort -R | head -n 1)
  VARA="${SHUF_OUT//$'\r'/}"
  echo "Choosing random effect"
fi

## Node.js effect parser
if [ ! -e $BIN_PATH/effects/$LEDTYPE/$VARA.opc ]; then
  echo "Node.js effect not found"
else
  LEDSTOP
  ln -sf $BIN_PATH/effects/$LEDTYPE/$VARA.opc $BIN_PATH/nodeopc/server/animations/opc
  /usr/bin/curl --silent --output /dev/null -d '{"playlistname":"Playlist"}' -H \
    "Content-Type: application/json" -X POST http://127.0.0.1:9387/api/playlists/play
  echo "Set LEDs to Node.js effect"
  exit
fi

if [ "$VARA" = "fc" ]; then
  LEDSTOP
  systemctl set-environment rpi_ledtype=$LEDTYPE rpi_fcsetup=fc$VARB.json
  systemctl restart rpi-fcserver 
  systemctl restart rpi-nodeopc
  echo "LEDs brightness changed to $VARB%"
  exit
fi

if [ "$VARA" = "stop" ]; then
  echo "Blanking effects"
fi

if [ "$VARA" = "pause" ]; then
  LEDSTOP
  exit
fi

## Python LED Effects
if [ "$VARA" = "rave" ] || [ "$VARA" = "chase" ] || \
   [ "$VARA" = "miami" ] || [ "$VARA" = "spark" ] || \
   [ "$VARA" = "stripes" ] || [ "$VARA" = "lava" ] ; then
  LEDSTOP
  systemctl set-environment rpi_fceffect=pyth-$VARA
  systemctl start rpi-fcleds
  echo "Set LEDs to Python effect"
  exit
fi

## Perl Effects
if [ "$VARA" = "noise3" ] || [ "$VARA" = "blocks" ] || \
   [ "$VARA" = "mandelbrot" ] || [ "$VARA" = "multitomaton" ] || \
   [ "$VARA" = "ripple" ] || [ "$VARA" = "random" ] ; then
  LEDSTOP 	
  systemctl set-environment rpi_fceffect=perl-$VARA
  systemctl start rpi-fcleds
  echo "Set LEDs to Perl effect"
  exit
fi

## Java Effects
if [ "$VARA" = "rainbow" ] || [ "$VARA" = "spectro" ] ; then
  LEDSTOP 	
  systemctl set-environment rpi_fceffect=java-$VARA
  systemctl start rpi-fcleds
  echo "Set LEDs to Java effect"
  exit
fi

# Spectro Gain Adjust
if [ "$VARA" = "plus" ]; then
  export DISPLAY=":1"
  xdotool key plus
  exit
fi

if [ "$VARA" = "minus" ]; then
  export DISPLAY=":1"
  xdotool key minus
  exit
fi

## Solid Color
LEDSTOP
$BIN_PATH/effects/colorscan "$VARA" | $BIN_PATH/effects/opc_client 127.0.0.1:7890
echo "Set LEDs to solid color"
exit 
