#!/bin/bash
########################################
# LED Effects Wrapper (ran from PHP-API)
########################################

## Read Input Arguments
VARA=$1
VARB=$2

## Run in background, discard returned output
nohup /opt/rpi/leds.sh "$VARA" "$VARB" > /dev/null 2>&1 &

exit