#!/bin/bash
##
## RPi Server v5 for Raspberry Pi by Ben Provenzano III
#### 2nd Stage ####

case "$1" in

boot)
## Light Web Server
systemctl restart lighttpd
## Unified Web Server
systemctl restart rpi-urserver
## Loop Movies from USB Drive
#systemctl restart rpi-vidlooper
## Start X11 Server
#su -c "/opt/rpi/init x11" -s /bin/sh pi
## Start Web Kiosk Interface
#su -c "/opt/rpi/init kiosk" -s /bin/sh pi
## Start On-Screen Keyboard
#su -c "/opt/rpi/init osk" -s /bin/sh pi
## Bluetooth Audio
#systemctl start hciuart
#systemctl start bluetooth
#systemctl start bt-agent@hci0
#systemctl start bluealsa-aplay
## Reset Bluetooth Connections
#sleep 5
#/opt/rpi/init resetbt
## Disable HDMI (saves 30mA of power draw)
#/opt/vc/bin/tvservice -o
## Auto Hotspot
sleep 60 # only run if bluetooth not connected
if [ ! -e /tmp/bt.connected ]; then
   # (on boot only)	
   systemctl start rpi-netdetect.service
   # (runs every 5min)	
   #systemctl start rpi-netdetect.timer
fi
exit
;;

usbplug)
## This script is ran after USB drive attached and when its removed.
echo "no function assigned"
exit
;;






        *)
          echo "RPi Server v3 for Raspberry Pi"
	      echo "  by Ben Provenzano III"
	      echo " "
	      echo "Enter a valid command line argument."
          exit 1
          ;;
    esac
