#!/bin/bash
##
## RPi Server v5 for Raspberry Pi by Ben Provenzano III
#### 2nd Stage ####

case "$1" in

boot)
## Activity LED Mode
echo actpwr | tee /sys/class/leds/led0/trigger &>/dev/null
## Start X11 Server
#systemctl start rpi-x11
## AirPlay Support
#systemctl start rpi-airplay
## Bluetooth Audio
#systemctl start hciuart
#systemctl start bluetooth
#systemctl start bt-agent@hci0
#systemctl start bluealsa-aplay
## Reset Bluetooth Connections
#sleep 5
#/opt/rpi/init resetbt
## Disable HDMI (saves 30mA of power draw)
#tvservice -o
exit
;;

usbplug)
## This script is ran after USB drive attached and when its removed.
echo "no function assigned"
exit
;;

        *)
          echo "RPi Server v3 for Raspberry Pi"
	        echo "  by Ben Provenzano III"
	        echo " "
	        echo "Enter a valid command line argument."
          exit 1
          ;;
    esac
