#!/bin/bash
##
## Pi Web Terminal System Configuration API 
##
EXIT_ROUTINE() {
  TRAILER=$(date)
  TRAILER+=" ("
  TRAILER+=$(hostname)
  TRAILER+=")"
  echo "$TRAILER" &>> $LOGFILE
  echo " " &>> $LOGFILE
  exit
}

LOGFILE="/var/www/html/ram/sysout.txt"

if [ "$1" == "" ]; then
  echo "no argument." &>> $LOGFILE  
  EXIT_ROUTINE
fi
## Wi-Fi setup API
if [ "$1" == "confwpa" ]; then
  ## Decode base64
  BASE64_IN=$(echo "$2" | sed "s|-|+|g" | sed "s|_|/|g" | sed "s|@|=|g")
  WPADATA=$(openssl enc -base64 -d <<< "$BASE64_IN")
  rm -f /tmp/wifidata
  echo -e "$WPADATA" > /tmp/wifidata
  ## Copy configuration to boot partition
  /opt/rpi/init cpwifi
  echo "set Wi-Fi configuration." &>> $LOGFILE
  echo " " &>> $LOGFILE
  EXIT_ROUTINE	
fi
## Server control
if [ "$1" == "server" ]; then
	if [ "$2" == "clearlog" ]; then
	  truncate -s 0 $LOGFILE
    neofetch | sed 's/\x1B[@A-Z\\\]^_]\|\x1B\[[0-9:;<=>?]*[-!"#$%&'"'"'()*+,.\/]*[][\\@A-Z^_`a-z{|}~]//g' &>> $LOGFILE
    EXIT_ROUTINE
	fi
  if [ "$2" == "showwpa" ]; then
    echo "current Wi-Fi configuration:" &>> $LOGFILE
    cat /boot/wpa.conf &>> $LOGFILE
    echo " " &>> $LOGFILE
    echo "network configuration:" &>> $LOGFILE
    ifconfig &>> $LOGFILE
    EXIT_ROUTINE
  fi
  echo "sent $2 system command." &>> $LOGFILE
	/opt/rpi/init "$2" &>> $LOGFILE
  EXIT_ROUTINE
else
## Application control
  /opt/rpi/main "$1" "$2" &>> $LOGFILE
  EXIT_ROUTINE
fi

exit
