#!/bin/bash
##
## Pi Web Terminal System Configuration API 
##
LOGFILE="/var/www/html/ram/sysout.txt"
if [[ "$1" == "" ]]
then
  echo "no argument." &>> $LOGFILE  
  exit
fi
## Wi-Fi setup API
if [ "$1" = "confwpa" ]; then
  echo "applying Wi-Fi configuration..." &>> $LOGFILE
  ## Decode base64
  WPADATA=$(echo "$2" | base64 --decode)
  ## Split by delimiter
  DELIM="|$|"
  SSID=${WPADATA%"$DELIM"*}
  PWD=${WPADATA#*"$DELIM"}
  ## Write to configuration
  echo "SSID: $SSID" &>> $LOGFILE
  echo "Password: $PWD" &>> $LOGFILE
  exit	
fi
## Server control
if [ "$1" = "server" ]; then
	if [[ $2 == "clearlog" ]]
	then
	  truncate -s 0 $LOGFILE
	else
	  /opt/rpi/init "$2" &>> $LOGFILE
	fi
else
## Application control
  /opt/rpi/main "$1" "$2" &>> $LOGFILE
fi
TRAILER=$(date)
TRAILER+=" ("
TRAILER+=$(hostname)
TRAILER+=")"
echo "$TRAILER" &>> $LOGFILE
echo " " &>> $LOGFILE
exit
