#!/bin/bash
###########################################################
#### Camera Video Copy Script by Ben Provenzano III v3 ####
###########################################################

function COPYFILE {
    blocksize=4096
    count=256
    blocks_read=0
    # check if the file exists on source, remove if found
    if [ -e $destfile ]; then
	  timeout 500 rm -f "$destfile"
	  # check the status after command is finished
	  status=$?
	  # if command was killed by timeout or rm returned error (I/O error)
	  if [[ ("$status" -gt 100 ) || ("$status" -eq 1) ]]
	  then
	    # log path to the source file into log
	    echo "Timeout exceeded could not delete, $destfile $(date)" >> $LOGFILE
	    # exit function
	    return
	  fi      
    fi  
    # check the size of source file in bytes
    filesize=$(stat -c%s "$sourcefile")
    #echo "Copy of $sourcefile to $destfile started:"
    # copy until all bytes of file are not copied
    while [ "$((blocks_read*blocksize))" -lt "$filesize" ]
    do
	# copy 4096 bytes to destination file with timeout in seconds
	timeout 60 dd if="$sourcefile" iflag=nofollow status=none \
	  bs=$blocksize count=$count skip=$blocks_read  >> "$destfile"
	# check the status after command is finished
	status=$?
	# if command was killed by timeout or dd returned error (I/O error)
	if [[ ("$status" -eq 124 ) || ("$status" -eq 1) ]]
	then
	    # delete destination file
	    rm -f "$destfile"
	    # log path to the source file into log
	    echo "Timeout exceeded $destfile not copied, $(date)" >> $LOGFILE
	    # copy video to flash drive if server or google drive copy fails
	    FLASHDRV="yes" 
	    # exit function
	    return
	fi
	# update number of bytes copied
	blocks_read=$((blocks_read+count))
    done
    #echo "Copy of $sourcefile to $destfile finished"
}

## Read camera name (1st arg)
CAM_NAME=$1
## Read file name (2nd arg)
FILE_NAME=$2

## Folder paths
SERVER_PATH="/mnt/smb/Cameras/Current"
GDRIVE_PATH="/mnt/gsync/Current"
FLASH_PATH="/media/usb0/cameras"

## Log file path
if [ ! -e $FLASH_PATH ]; then
  LOGFILE="/tmp/motioncopy.log"
else
  LOGFILE="$FLASH_PATH/motioncopy.log"
fi  

## Delete videos from RAM cache if size limit exceeded 
if [ $FILE_NAME = "spacechk" ]; then
  ## Turn on status LED for 10 seconds
  screen -dm sudo /opt/rpi/main redpulse	
  rm -f /tmp/camcleanup.vars
  du -sh -t275000000 /mnt/ramdisk | awk -F" " '{print $2}' > /tmp/camcleanup.vars
  if [[ -s /tmp/camcleanup.vars ]] ; then
    echo "RAM cache over 275MB moving files! $(date)" >> $LOGFILE
    if [ ! -e $FLASH_PATH ]; then
      echo "Flash drive not connected, discarding videos $(date)" >> $LOGFILE
    else
      DEST_PATH="$FLASH_PATH/$CAM_NAME"
	  if [ ! -e "$DEST_PATH" ]; then
	    mkdir -p "$DEST_PATH"
	  fi
      cp -rvf /mnt/ramdisk/"$CAM_NAME"/* "$DEST_PATH"/
    fi
    rm -rf /mnt/ramdisk/*
  fi
mkdir -p /mnt/ramdisk/"$CAM_NAME"
exit
fi

## Server copy (I)
if [ ! -e $SERVER_PATH ]; then
  SERVER="na"	
  echo "Server not connected, $(date)" >> $LOGFILE
else
  DEST_PATH="$SERVER_PATH/$CAM_NAME"
  if [ ! -e "$DEST_PATH" ]; then
    mkdir -p "$DEST_PATH"
  fi
  sourcefile="$FILE_NAME.mp4"
  destfile="$DEST_PATH/$(basename $FILE_NAME.mp4)"
  if [ -e "$sourcefile" ]; then
    COPYFILE
  fi
fi

## Google drive copy (II)
if ping -W 10 -c 1 8.8.8.8 > /dev/null 2> /dev/null
then
  DEST_PATH="$GDRIVE_PATH/$CAM_NAME"
  if [ ! -e "$DEST_PATH" ]; then
    mkdir -p "$DEST_PATH"
  fi
  sourcefile="$FILE_NAME.mp4"
  destfile="$DEST_PATH/$(basename $FILE_NAME.mp4)"
  if [ -e "$sourcefile" ]; then
    COPYFILE
  fi  
else
  echo "Google ping exceeded 10 seconds, $(date)" >> $LOGFILE
  if [ "$SERVER" = "na" ]; then
    FLASHDRV="yes"   
  fi 
fi

## Flash drive copy (III)
if [ "$FLASHDRV" = "yes" ]; then
  if [ ! -e $FLASH_PATH ]; then
    echo "Flash drive not connected, discarding video $(date)" >> $LOGFILE
  else
    echo "Copying video to flash drive, $(date)" >> $LOGFILE
    DEST_PATH="$FLASH_PATH/$CAM_NAME"
	if [ ! -e "$DEST_PATH" ]; then
	  mkdir -p "$DEST_PATH"
	fi
	sourcefile="$FILE_NAME.mp4"
	destfile="$DEST_PATH/$(basename $FILE_NAME.mp4)"
    if [ -e "$sourcefile" ]; then
      COPYFILE
    fi
  fi
fi 

## Delete video from RAM Disk
rm -f "$FILE_NAME.mp4"
exit