#!/bin/bash
## INIT Script by Ben Provenzano III

case "$1" in

##############################################
########### SYSTEM PROGRAMS ##################

active)
echo "Active services."
systemctl list-units --type=service --state=active
exit
;;

running)
echo "Running services."
systemctl list-units --type=service --state=running
exit
;;

timers)
## List Active Timers
systemctl list-timers --all
exit
;;

loadtimes)
## Display list of system daemons and startup times
systemd-analyze blame
exit
;;

update)
### Debian System Update
echo " "
echo "System must be in read-write mode."
echo " "
df -h
read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
apt-get -y update --allow-releaseinfo-change
apt-get upgrade
apt-get dist-upgrade
apt-get autoremove -y
apt-get clean -y
#pip install --upgrade pip
echo " "
echo "Re-enable read-only mode after rebooting!"
exit
;;

        *)
          echo "Init Script v2"
	        echo "by Ben Provenzano III"
	        echo " "
	        echo "Enter Valid Arguments."
          echo " "
          echo "update - Update/Upgrade System"
          echo "loadtimes - Startup Services"
          echo "active - Active Services"
          echo "running - Running Services"
          echo " "
          exit 1
          ;;
    esac   
