#!/bin/bash
###########################################################
####### LED parser script by Ben Provenzano III v12 #######
###########################################################

## Read Input Arguments
VARA=$1
VARB=$2

if [ -e /opt/rpi/ledsync.txt ]; then
  cat /opt/rpi/ledsync.txt | xargs -P 10 -I % \
    /usr/bin/curl -N -f -m 10 --silent --data \
    "var=$VARB&arg=$VARA&action=leds" http://%:9300/exec.php
else
  echo "ledsync.txt not found."    
fi
exit


