#!/bin/bash
##
###########################################################
## Main Home Automation Script by Ben Provenzano III v18 ##
###########################################################
###########################################################
## Do not use the screen command in this script ##

## Transmit POST request to host
CALLAPI(){
/usr/bin/curl --silent --fail --ipv4 --no-buffer --max-time 15 \
 --retry 3 --retry-all-errors --retry-delay 1 --no-keepalive --data \
 "var=$CMDARG&arg=$CMD&action=main" http://$TARGET.local/exec.php	
}

## Read the 2nd Argument
CMDARG=$2

## Read the 1st Argument
case "$1" in

####################################

relax)
### Relax Sounds Playback
if [ ! -e /var/lock/rpi/relaxrec.save ]; then
  TARGET="hifimini"
else
  TARGET="hifi"
  ## Optical Decoder Input
  /opt/rpi/xmit coaxial
  ## Preamp DAC Input
  /opt/rpi/xmit dac
fi
## Play Audio in Loop on System
CMD="relax"
CALLAPI
exit
;;

stoprelax)
## Stop Relax Sounds
if [ ! -e /var/lock/rpi/relaxrec.save ]; then
  TARGET="hifimini"
else
  TARGET="hifi"
  ## USB Decoder Input
  /opt/rpi/xmit usb
  ## Preamp DAC Input
  /opt/rpi/xmit dac
fi
CMD="stoprelax"
CALLAPI
exit
;;

### Relax Sounds Volume Up
relaxvup)
if [ ! -e /var/lock/rpi/relaxrec.save ]; then
  TARGET="hifimini"
  CMDARG=""
  CMD="vup"	
  CALLAPI
else
  /opt/rpi/xmit upc
fi   
exit
;;

### Relax Sounds Volume Down
relaxvdwn)
if [ ! -e /var/lock/rpi/relaxrec.save ]; then
  TARGET="hifimini"
  CMDARG=""
  CMD="vdwn"		
  CALLAPI
else
  /opt/rpi/xmit dwnc
fi
exit
;;

## Toggle Relax Sounds Playback Device
relaxhost)
if [ ! -e /var/lock/rpi/relaxrec.save ]; then
  touch /var/lock/rpi/relaxrec.save
else
  rm -f /var/lock/rpi/relaxrec.save 
fi
exit
;;

####################################
## Automated Multi-Functions

lights)
## Toggle Lamps
if [ ! -e /var/lock/rpi/lights.save ]; then
  touch /var/lock/rpi/lights.save
  ## Main Lamp
  /opt/rpi/xmit rfc1 on
  ## Dresser Lamp
  /opt/rpi/xmit rfa2 on
else
  ## Turn all lights off
  rm -f /var/lock/rpi/lights.save
  ## Main Lamp
  /opt/rpi/xmit rfc1 off
  ## Dresser Lamp
  /opt/rpi/xmit rfa2 off
fi
exit
;;

lightson)
## Turn all lights on
touch /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
exit
;;

lightsoff)
## Turn all lights off
rm -f /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
exit
;;

allon)
touch /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
## Desk Light
/opt/rpi/xmit rfb1 on
## LEDwalls
/opt/rpi/leds candle
sleep 2.5
/opt/rpi/leds fc 60
exit
;;

alloff)
## Turn all lights off
rm -f /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
## Desk Light
/opt/rpi/xmit rfb1 off
## Blank LEDwalls
/opt/rpi/leds stop
exit
;;

## Audio Power
hifion)
if ping -W 2 -c 1 hifi.local > /dev/null 2> /dev/null
then
  echo "Host is up"
else
  /opt/rpi/xmit pwrhifi
fi
exit
;;
##
hifioff)
if ping -W 2 -c 1 hifi.local > /dev/null 2> /dev/null
then
  /opt/rpi/xmit pwrhifi
else
  echo "Host is down"
fi
exit
;;

## PC Power
pcon)
if ping -W 2 -c 1 wkst.home > /dev/null 2> /dev/null
then
  echo "Host is up"
else
  /opt/rpi/xmit rfb3
fi
exit
;;
##
pcoff)
if ping -W 2 -c 1 wkst.home > /dev/null 2> /dev/null
then
  /opt/rpi/xmit rfb3
else
  echo "Host is down"
fi
exit
;;

submute)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer mute/disable
  /opt/rpi/xmit subpwr
fi
exit
;;

subup)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer volume up
  /opt/rpi/xmit subup
fi
exit
;;

subdwn)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer volume down
  /opt/rpi/xmit subdwn
fi
exit
;;

subs)
## Toggle volume control to subwoofers
if [ ! -e /var/lock/rpi/subs.enabled ]; then
   touch /var/lock/rpi/subs.enabled
else
   rm -f /var/lock/rpi/subs.enabled
fi
exit
;;

autodac)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Auto Decoder Input
/opt/rpi/xmit inauto
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

usb)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## USB Decoder Input
/opt/rpi/xmit usb
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

## Coax Input
coax)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Coaxial Decoder Input
/opt/rpi/xmit coaxial
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

## Optical Input
opt)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Optical Decoder Input
/opt/rpi/xmit optical
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

roomon)
## Main Lamp On
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
## Desk Light
/opt/rpi/xmit rfb1 on
## Desktop Power
/opt/rpi/xmit rfb2 on
## PC Power On
if ping -W 2 -c 1 wkst.home > /dev/null 2> /dev/null
then
  echo "Host is up"
else
  /opt/rpi/xmit rfb3
fi
## LEDwalls
/opt/rpi/leds prism
sleep 3.5
/opt/rpi/leds fc norm
exit
;;

roomoff)
## Main Lamp Off
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
## Desk Light
/opt/rpi/xmit rfb1 off
## Desktop Power
/opt/rpi/xmit rfb2 off
## PC Power Off
if ping -W 2 -c 1 wkst.home > /dev/null 2> /dev/null
then
  /opt/rpi/xmit rfb3
else
  echo "Host is down"
fi
## Audio System Power Off
if ping -W 2 -c 1 hifi.local > /dev/null 2> /dev/null
then
  /opt/rpi/xmit pwrhifi
else
  echo "Host is down"
fi
## Blank LEDwalls
/opt/rpi/leds stop
exit
;;

unifi)
## Toggle Unifi Controller
SYSDSTAT="$(systemctl is-active unifi.service)"
if [ "${SYSDSTAT}" = "active" ]; then
  echo "UniFi running, stopping service..."
  systemctl stop unifi
else 
  echo "UniFi not running, starting service..."  
  systemctl start unifi
  echo "access at 'https://automate.home:8443/' "
fi
exit
;;

### Examples of URL strings ###
# http://automate:9300/exec.php?var=&arg=lightson&action=main
# http://automate:9300/exec.php?var=&arg=lightsoff&action=main
# http://automate:9300/exec.php?var=prism&arg=video&action=leds
###############################


        *)
          echo "Automate Server"
	        echo "  by Ben Provenzano III "
	        echo " "
	        echo "Enter a valid command line argument."
          exit 1
          ;;
    esac   
