#!/bin/sh

### Unifed Remote Server Startup Script

OPENSSL_CONF=/etc/ssl/

echo "Starting Server..."

rm -rf /root/.urserver
mkdir -p /root/.urserver
touch /root/.urserver/urserver.pid
ln -sf /dev/null /root/.urserver/urserver.log
/opt/rpi/urserver --remotes=/opt/rpi/remotes --pidfile=/root/.urserver/urserver.pid --daemon

exit 0