#!/bin/bash
## Cameras Pi Configuration Setup Script v6.0
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
mount -o remount,ro /boot

## Google Drive Support
apt-get install -y --no-upgrade rclone fuse
cp -f $BIN/modconf/rpi-rclone.service /etc/systemd/system/
chmod -f 644 /etc/systemd/system/rpi-rclone.service
chown -f root:root /etc/systemd/system/rpi-rclone.service
rm -f /root/.config/rclone/rclone.conf
if [ ! -e /media/usb0/rclone/rclone.conf ]; then
  echo "API key not found on flash drive, running setup..."
  echo "Create new remote named 'gsync' and attach to Google Drive"
  rclone config
  mkdir -p /media/usb0/rclone
  cp -fv /root/.config/rclone/rclone.conf /media/usb0/rclone/
  cat /media/usb0/rclone/rclone.conf
  chmod -R 777 /media/usb0/rclone
fi

## Camera Motion Server
if [ ! -e /usr/bin/motion ]; then
  apt-get install -y --no-upgrade libmicrohttpd12
  dpkg -i /opt/rpi/pkgs/pi_buster_motion_4.3.2-1_armhf.deb
  systemctl stop motion
fi
groupadd motion
useradd motion -g motion --shell /bin/false
groupmod -g 1005 motion
usermod -u 1005 motion
cp -f $BIN/modconf/motion /etc/default/
chmod 644 /etc/default/motion
chown root:root /etc/default/motion
cp -f $BIN/modconf/motion.conf /etc/motion/
chmod 644 /etc/motion/motion.conf
chown root:root /etc/motion/motion.conf
cp -fr $BIN/modconf/camera*.conf /etc/motion/
chmod -R 644 /etc/motion/camera*.conf
chown -R root:root /etc/motion/camera*.conf
systemctl disable motion

## Camera Cleanup Timer
cp -f $BIN/modconf/rpi-camcleanup.service /etc/systemd/system/
chmod -f 644 /etc/systemd/system/rpi-camcleanup.service
chown -f root:root /etc/systemd/system/rpi-camcleanup.service
cp -f $BIN/modconf/rpi-camcleanup.timer /etc/systemd/system/
chmod -f 644 /etc/systemd/system/rpi-camcleanup.timer
chown -f root:root /etc/systemd/system/rpi-camcleanup.timer

## AutoFS Configuration
cp -f $BIN/modconf/auto.master /etc/
chmod 644 /etc/auto.master
chown root:root /etc/auto.master
cp -f $BIN/modconf/auto.map /etc/
chmod 644 /etc/auto.map
chown root:root /etc/auto.map
cp -f $BIN/modconf/auto.creds /etc/
chmod 400 /etc/auto.creds
chown root:root /etc/auto.creds
mkdir -p /mnt/smb

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main
ln -sf /opt/rpi/camcleanup /usr/bin/camcleanup

exit
