#!/bin/bash
###########################################################
## TouchPi main script by Ben Provenzano III ###############
###########################################################
###########################################################

case "$1" in

boot)
## LCD Brightness
sh -c 'echo "120" > /sys/class/backlight/rpi_backlight/brightness'
## Light Web Server
systemctl start lighttpd
## Start X Interface
su -c "/opt/rpi/init x11" -s /bin/sh pi
## Start X Programs
su -c "/opt/rpi/main xprgms" -s /bin/sh pi
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Auto Hotspot (on boot only)
sleep 60
systemctl start rpi-netdetect.service
exit
;;

xprgms)
## Connect to X
export DISPLAY=":0"
## LCD Sleep Mode
/opt/rpi/lcdsleep.sh &
## X11 Web Kiosk
killall chromium
sleep 1.25
## Clear Cache
rm -r ~/.cache/chromium
## Start Browser 
chromium --kiosk --no-first-run --disable-plugins --disk-cache-size=800000 --media-cache-size=800000 \
 --enable-features=OverlayScrollbar,OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbarFlashWhenMouseEnter \
 --incognito --disable-restore-session-state --disable-session-crashed-bubble --noerrdialogs --disable-infobars \
 http://automate.home/ &
exit
;;

lcdon)
## LCD on
sudo sh -c 'echo 0 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdoff)
## LCD off
sudo sh -c 'echo 1 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdlow)
## Low LCD Brightness
sudo sh -c 'echo "50" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd50)
## 50% LCD Brightness
sudo sh -c 'echo "100" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd75)
## 75% LCD Brightness
sudo sh -c 'echo "170" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd100)
## Full LCD Brightness
sudo sh -c 'echo "255" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

	    
    *)
      echo "TouchPi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
	  echo "lcdoff - Turn off display"
	  echo "lcdon - Turn on display"
	  echo "lcdlow - Low display brightness"
	  echo "lcd50 - 50% display brightness"
	  echo "lcd75 - 75% display brightness"
	  echo "lcd100 - 100% display brightness"
      exit 1
      ;;
    esac
