#!/bin/bash
###########################################################
## TouchPi main script by Ben Provenzano III ##############
###########################################################
###########################################################

case "$1" in

boot)
## LCD Brightness
sh -c 'echo "120" > /sys/class/backlight/rpi_backlight/brightness'
## Light Web Server
systemctl start lighttpd
## Start X Interface
systemctl start rpi-x11
systemctl start rpi-restartx.timer
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Auto Hotspot (on boot only)
sleep 60
systemctl start rpi-netdetect.service
exit
;;

x11)
## Desktop environment
## Start as pi user!
export DISPLAY=":0"
pkill Xorg
sleep 1.25
rm -rf /home/pi/.cache/menus
rm -rf /home/pi/.cache/lxsession
mkdir -p /home/pi/.cache/lxsession/LXDE
ln -sf /dev/null /home/pi/.cache/lxsession/LXDE/run.log
rm -rf /home/pi/.cache/openbox
mkdir -p /home/pi/.cache/openbox
ln -sf /dev/null /home/pi/.cache/openbox/openbox.log
echo "Starting X11-LXDE..."
startx &
sleep 4.25
## Disable Screen Blanking
xset s 0 0 s noblank s noexpose
xset -dpms
## LCD Sleep Mode
/opt/rpi/lcdsleep.sh &
#################
## X11 Web Kiosk
killall chromium
sleep 1.25
## Clear Cache
rm -rf /home/pi/.config/chromium
rm -rf /home/pi/.cache/chromium
## Start Browser 
chromium --kiosk --no-first-run --disable-plugins --disk-cache-size=80000 --media-cache-size=80000 \
 --enable-features=OverlayScrollbar,OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbarFlashWhenMouseEnter \
 --incognito --disable-restore-session-state --disable-session-crashed-bubble --noerrdialogs --disable-infobars \
 http://automate.home/ &
 ################
exit
;;

lcdon)
## LCD on
sudo sh -c 'echo 0 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdoff)
## LCD off
sudo sh -c 'echo 1 > /sys/class/backlight/rpi_backlight/bl_power'
exit
;;

lcdlow)
## Low LCD Brightness
sudo sh -c 'echo "50" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd50)
## 50% LCD Brightness
sudo sh -c 'echo "100" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd75)
## 75% LCD Brightness
sudo sh -c 'echo "170" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

lcd100)
## Full LCD Brightness
sudo sh -c 'echo "255" > /sys/class/backlight/rpi_backlight/brightness'
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

	    
    *)
      echo "TouchPi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
	  echo "lcdoff - Turn off display"
	  echo "lcdon - Turn on display"
	  echo "lcdlow - Low display brightness"
	  echo "lcd50 - 50% display brightness"
	  echo "lcd75 - 75% display brightness"
	  echo "lcd100 - 100% display brightness"
      exit 1
      ;;
    esac
