#!/bin/sh
## LEDwall Configuration Script v7.0

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
mount -o remount,ro /boot

## Enable LED remotes
ln -sf /opt/rpi/effects/remotes /opt/rpi/remotes/leds

## Set LEDgrid Type
rm -f /opt/rpi/ledtype.txt
if ping -c 1 10.177.1.1 > /dev/null 2> /dev/null
then
  LEDTYPE="8x8revgrid"
  echo "Home domain detected, setting LEDtype to $LEDTYPE..."
  echo "$LEDTYPE" > /opt/rpi/ledtype.txt
else
  LEDTYPE="8x8grid"
  echo "Home domain not detected, setting LEDtype to $LEDTYPE..."
  echo "$LEDTYPE" > /opt/rpi/ledtype.txt
fi

## Stage II - Set module name to configs
if [ ! -e $BIN/modconf/brand.txt ]; then
echo "Skip module naming."
else
echo "Setting module name."
## Module specific home page
if ping -c 1 10.177.1.1 > /dev/null 2> /dev/null
then
  echo "Home domain detected, installing custom web page..."
  cp -fv $BIN/modconf/client.home.html /opt/rpi/manager/client.html
  chmod 644 /opt/rpi/manager/client.html
  chown root:root /opt/rpi/manager/client.html
else
  echo "Home domain not detected, installing standard web page..."
  cp -fv $BIN/modconf/client.html /opt/rpi/manager/
  chmod 644 /opt/rpi/manager/client.html
  chown root:root /opt/rpi/manager/client.html
fi
## Set module name to unified server
sed -i "s/RaspberryPi/$MODNAME/g" /opt/rpi/manager/client.html
sed -i "s/raspberrypi/$HOSTNAME/g" /opt/rpi/manager/client.html
fi

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

## Routed Hotspot Configuration
#cp -f /etc/dnsmasq.routed /etc/dnsmasq.conf
#chmod 644 /etc/dnsmasq.conf
#chown root:root /etc/dnsmasq.conf

## Change Web Server Default Theme
/opt/rpi/init dgreen

exit
