#!/bin/bash
###########################################################
####### LED parser script by Ben Provenzano III v12 #######
###########################################################

## Read Input Arguments
VARA=$1
VARB=$2

############### START OF MAIN PROCESS ###############

## LEDsync Command Dispatcher (make sure .txt file has newline at end)
if [ -e /opt/rpi/ledsync.txt ]; then
  LEDFILE='/opt/rpi/ledsync.txt'
  exec 4<$LEDFILE
  while read -u4 PSYNC ; do
      echo "Sending $VARA command to $PSYNC LED server..."
      /usr/bin/screen -dm /usr/bin/curl -N -f -m 10 --silent --data "var=$VARB&arg=$VARA&action=leds" http://$PSYNC:9300/exec.php
      sleep 0.25
  done
fi

exit

