#!/bin/bash
##
###########################################################
## Main Home Automation Script by Ben Provenzano III v17 ##
###########################################################
###########################################################

## Read the 2nd Argument
ARG2=$2

## Read the 1st Argument
case "$1" in

### Relaxation Sound Playback
stoprelax)
/usr/bin/curl -N -f -m 5 --silent "http://system/exec.php?var=&arg=stoprelax&action=main"
## USB Decoder Input
/opt/rpi/xmit usb
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

relax)
killall -s KILL -w mpv
## Play Audio in Loop
/usr/bin/curl -N -f -m 5 --silent "http://system/exec.php?var=$ARG2&arg=relax&action=main"
## Optical Decoder Input
/opt/rpi/xmit coaxial
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

## Automated Multi-Functions

lightson)
touch /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
## Desk Light
/opt/rpi/xmit rfb1 on
exit
;;

allon)
touch /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
## Desk Light
/opt/rpi/xmit rfb1 on
## LEDwalls
/opt/rpi/leds candle
sleep 2.5
/opt/rpi/leds fc 60
exit
;;

lightsoff)
## Turn all lights off
rm -f /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
## Desk Light
/opt/rpi/xmit rfb1 off
exit
;;

alloff)
## Turn all lights off
rm -f /var/lock/rpi/lights.save
## Main Lamp
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
## Desk Light
/opt/rpi/xmit rfb1 off
## Blank LEDwalls
/opt/rpi/leds stop
exit
;;

## Audio power
pwrhifi)
## Power audio system
/opt/rpi/xmit pwrhifi
## Reset sub volume token
rm -f /var/lock/rpi/subs.enabled
exit
;;
##
hifion)
if ping -c 1 system.home > /dev/null 2> /dev/null
then
  echo "Host is up"
else
  ## Power audio system
  /opt/rpi/xmit pwrhifi
  ## Reset sub volume token
  rm -f /var/lock/rpi/subs.enabled
fi
exit
;;
##
hifioff)
if ping -c 1 system.home > /dev/null 2> /dev/null
then
  ## Power audio system
  /opt/rpi/xmit pwrhifi
  ## Reset sub volume token
  rm -f /var/lock/rpi/subs.enabled
else
  echo "Host is down"
fi
exit
;;

## PC Power
pcon)
if ping -c 1 z97mx.home > /dev/null 2> /dev/null
then
  echo "Host is up"
else
  /opt/rpi/xmit rfb3
fi
exit
;;
##
pcoff)
if ping -c 1 z97mx.home > /dev/null 2> /dev/null
then
  /opt/rpi/xmit rfb3
else
  echo "Host is down"
fi
exit
;;

submute)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer mute/disable
  /opt/rpi/xmit subpwr
fi
exit
;;

subup)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer volume up
  /opt/rpi/xmit subup
fi
exit
;;

subdwn)
if [ -e /var/lock/rpi/subs.enabled ]; then
  ### Subwoofer volume down
  /opt/rpi/xmit subdwn
fi
exit
;;

subs)
## Toggle volume control to subwoofers
if [ ! -e /var/lock/rpi/subs.enabled ]; then
   touch /var/lock/rpi/subs.enabled
else
   rm -f /var/lock/rpi/subs.enabled
fi
exit
;;

autodac)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Auto Decoder Input
/opt/rpi/xmit inauto
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

usb)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## USB Decoder Input
/opt/rpi/xmit usb
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

## Coax Input
coax)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Coaxial Decoder Input
/opt/rpi/xmit coaxial
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

## Optical Input
opt)
## Reset volume tokens
rm -f /var/lock/rpi/subs.enabled
## Optical Decoder Input
/opt/rpi/xmit optical
## Preamp DAC Input
/opt/rpi/xmit dac
exit
;;

roomon)
## Main Lamp On
/opt/rpi/xmit rfc1 on
## Dresser Lamp
/opt/rpi/xmit rfa2 on
## Desk Light
/opt/rpi/xmit rfb1 on
## Desktop Power
/opt/rpi/xmit rfb2 on
## PC Power On
/opt/rpi/main pcon
## LEDwalls
/opt/rpi/leds prism
sleep 3.5
/opt/rpi/leds fc norm
exit
;;

roomoff)
## Main Lamp Off
/opt/rpi/xmit rfc1 off
## Dresser Lamp
/opt/rpi/xmit rfa2 off
## Desk Light
/opt/rpi/xmit rfb1 off
## Desktop Power
/opt/rpi/xmit rfb2 off
## PC Power Off
/opt/rpi/main pcoff
## Blank LEDwalls
/opt/rpi/leds stop
exit
;;

### Examples of URL strings ###
# http://automate:9300/exec.php?var=&arg=lightson&action=main
# http://automate:9300/exec.php?var=&arg=lightsoff&action=main
# http://automate:9300/exec.php?var=prism&arg=video&action=leds
###############################


        *)
          echo "Automate Server"
	        echo "  by Ben Provenzano III "
	        echo " "
	        echo "Enter a valid command line argument."
          exit 1
          ;;
    esac   
