#!/bin/bash
#### Homebridge on/off API
## by Ben Provenzano III
## run ./leds-hb on PROGRAM ARG1 ARG2 (ARG1 is used as statefile)
## run ./leds-hb off PROGRAM ARG1 ARG2 (ARG1 is used as statefile)

CMD=$2
ARG1=$3
ARG2=$4

case "$1" in

on)
if [ -f "/var/lock/rpi/hb-state.lock" ]; then
    echo ""  > /dev/null 2>&1
else
    touch /var/lock/rpi/hb-state.lock
    touch /var/lock/rpi/$ARG1.save
    /opt/rpi/$CMD $ARG1 $ARG2
    sleep 0.25
    rm -f /var/lock/rpi/$ARG1.save
    sleep 0.75
    rm -f /var/lock/rpi/hb-state.lock
fi
exit
;;

off)
if [ -f "/var/lock/rpi/hb-state.lock" ]; then
    echo ""  > /dev/null 2>&1
else
	rm -f /var/lock/rpi/$ARG1.save
    /opt/rpi/$CMD $ARG1 $ARG2
fi
exit
;;


   *)
        echo "No Arguments."
        exit 1
        ;;
   esac


