#!/bin/bash
### ONLY RUN ON THE SERVER!!
### AutoConfig - ProOS for Automate VM
### by Ben Provenzano III

## Reinstall / Upgrade Unifi Controller
REINIT_UNIFI="no"

## Update Sources
apt-get --yes update

## Install Packages
apt-get install -y --no-upgrade --ignore-missing dirmngr ca-certificates bpytop htop \
 apt-transport-https wget unzip gnupg rsync curl screen parallel ethtool avahi-daemon \
 libdbus-1-dev libdbus-glib-1-dev locales aptitude sudo gnupg scrub binutils ffmpeg pip

## Process Monitor Symlink
ln -sf /usr/bin/bpytop /usr/bin/htop
## Remove Packages
apt-get remove -y --purge cron anacron postfix apache2 apache2-data

## Replace Process Monitor
ln -sf /usr/bin/bpytop /usr/bin/htop

## UniFi controller
if [ ! -e /lib/systemd/system/unifi.service ] || [ "$REINIT_UNIFI" = "yes" ]; then
  wget https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh
  bash unifi-latest.sh
  systemctl disable unifi
fi

## Apple TV Control
pip install pyatv

## Install Replacement Logger
apt-get remove --purge -y rsyslog
apt-get install -y --no-upgrade busybox-syslogd
echo "Run command 'logread' to check system logs"
dpkg --purge rsyslog
rm -f /var/log/messages
rm -f /var/log/syslog

## System Configuration
cp /tmp/config/sysctl.conf /etc
chmod 644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf

## System Resources
rm -rf /opt/rpi
rm -rf /opt/system
mkdir -p /opt/system
cp /tmp/config/leds.sh /opt/system/leds
cp /tmp/config/main.sh /opt/system/main
cp /tmp/config/relaxloop.sh /opt/system/relaxloop
cp /tmp/config/ledsync.txt /opt/system/
chmod -R 755 /opt/system/*
chown -R root:root /opt/system
ln -sf /opt/system/main /opt/system/xmit

## Light Web Server
apt-get install -y --no-upgrade lighttpd
apt-get install -y --no-upgrade php-common php-cgi php php-mysql
## LightTPD Configuration
cp -f /tmp/config/lighttpd.conf /etc/lighttpd
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf
lighttpd-enable-mod fastcgi fastcgi-php; lighty-enable-mod fastcgi-php
ln -sf /etc/lighttpd/conf-available/10-fastcgi.conf /etc/lighttpd/conf-enabled/
ln -sf /etc/lighttpd/conf-available/15-fastcgi-php.conf /etc/lighttpd/conf-enabled/
ln -sf /usr/share/lighttpd/create-mime.conf.pl /usr/share/lighttpd/create-mime.assign.pl
systemctl disable lighttpd
systemctl restart lighttpd

## PHP Configuration
PHP_VERSION=$(php -v | tac -r | tail -n 1 | cut -d " " -f 2 | cut -c 1-3)
cp -rf /tmp/config/php.cgi.ini /etc/php/$PHP_VERSION/cgi/php.ini
chmod 644 /etc/php/$PHP_VERSION/cgi/php.ini
chown root:root /etc/php/$PHP_VERSION/cgi/php.ini
cp -rf /tmp/config/php.cli.ini /etc/php/$PHP_VERSION/cli/php.ini
chmod 644 /etc/php/$PHP_VERSION/cli/php.ini
chown root:root /etc/php/$PHP_VERSION/cli/php.ini
chown -R www-data:www-data /var/lib/php
chmod -R g+rx /var/lib/php
if [ -e /lib/systemd/system/phpsessionclean.service ]; then
  systemctl disable phpsessionclean.timer
  systemctl disable phpsessionclean.service
  rm -f /lib/systemd/system/phpsessionclean.timer
  rm -f /lib/systemd/system/phpsessionclean.service
fi

## Base website files
rm -r /var/www/html
mkdir -p /var/www/html
mv -f /tmp/config/html/* /var/www/html
chmod -R 775 /var/www/html
chown -R www-data:www-data /var/www/html
mkdir -p /var/www/sessions
chmod -R g+rx /var/www/sessions
chown -R www-data:www-data /var/www/sessions
mkdir -p /var/www/uploads
chmod -R g+rx /var/www/uploads
chown -R www-data:www-data /var/www/uploads

## Link external resources to web server
ln -sf /mnt/ramdisk /var/www/html/ram

##
## WWW Permissions (Network Web UI)
rm -f /etc/sudoers.d/www-perms
rm -f /etc/sudoers.d/www-nopasswd
rm -f /etc/sudoers.d/www-mod-nopasswd
sh -c "touch /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(ALL) NOPASSWD:/opt/system/main*\" >> /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(ALL) NOPASSWD:/opt/system/init\" >> /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(ALL) NOPASSWD:/opt/system/leds\" >> /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(ALL) NOPASSWD:/opt/system/xmit\" >> /etc/sudoers.d/www-perms"
chown root:root /etc/sudoers.d/www-perms
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/www-perms
chmod u=r,g=r,o= /etc/sudoers.d/www-perms
##
## Nobody User Permissions (THD Hotkeys)
rm -f /etc/sudoers.d/nobody-perms
sh -c "touch /etc/sudoers.d/nobody-perms"
sh -c "echo \"nobody ALL=(ALL) NOPASSWD:/opt/system/main*\" >> /etc/sudoers.d/nobody-perms"
sh -c "echo \"nobody ALL=(ALL) NOPASSWD:/opt/system/init\" >> /etc/sudoers.d/nobody-perms"
sh -c "echo \"nobody ALL=(ALL) NOPASSWD:/opt/system/leds\" >> /etc/sudoers.d/nobody-perms"
sh -c "echo \"nobody ALL=(ALL) NOPASSWD:/opt/system/xmit\" >> /etc/sudoers.d/nobody-perms"
chown root:root /etc/sudoers.d/nobody-perms
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/nobody-perms
chmod u=r,g=r,o= /etc/sudoers.d/nobody-perms

## Relax Loop Service
cp -f /tmp/config/relaxloop.service /etc/systemd/system/
chmod 644 /etc/systemd/system/relaxloop.service
chown root:root /etc/systemd/system/relaxloop.service
systemctl disable relaxloop

## Boot Service
cp -f /tmp/config/rc.local /etc/
chmod 755 /etc/rc.local
chown root:root /etc/rc.local
cp -f /tmp/config/rc-local.service /etc/systemd/system/
chmod 644 /etc/systemd/system/rc-local.service
chown root:root /etc/systemd/system/rc-local.service
systemctl enable rc-local

## Disable Root Password
passwd -d root

## Auto SSH Login Key for root
mkdir -p /root/.ssh
cp -f /tmp/config/authorized_keys /root/.ssh/

## SSH Configuration
cp -f /tmp/config/sshd_config /etc/ssh/
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

## Profile Configuration
cp -f /tmp/config/profile /root/.profile
chmod 755 /root/.profile
chown root:root /root/.profile
touch /root/.hushlogin
chmod 644 /root/.hushlogin
chown root:root /root/.hushlogin

## Clean-up
rm -f /etc/systemd/system/urserver.service
systemctl daemon-reload
rm -rf /tmp/config/
apt-get autoremove -y
apt-get clean -y
apt-get autoclean -y
exit
