#!/bin/bash
###########################################################

## Arduino's Serial Port
ARDUINO_PORT="ttyUSB0"

LOCK_FILE="/tmp/zterm.lock"

## Read Command-Line Arguments
ARG1=$1
ARG2=$2

ZTERM_COM() {
local CMD_DATA="$1"
  # Only allow one instance
  if { set -C; 2>/dev/null > $LOCK_FILE; }; then
    trap "rm -f $LOCK_FILE" EXIT
  else
    echo "lock file exists exiting..."
    exit
  fi
  /usr/bin/ztermcom $CMD_DATA
}

case "$ARG1" in

boot)
## Start amplifier communication
ln -sf /dev/$ARDUINO_PORT /dev/zterm-tty
ZTERM_COM "i"
exit
;;

serialmon)
/opt/rpi/arduino-cli monitor -p /dev/$ARDUINO_PORT \
  -b arduino:avr:uno --config 9600
exit
;;

out1off)
ZTERM_COM "10001"
exit
;;

out1on)
ZTERM_COM "10002"
exit
;;

out2off)
ZTERM_COM "10003"
exit
;;

out2on)
ZTERM_COM "10004"
exit
;;

out3off)
ZTERM_COM "10005"
exit
;;

out3on)
ZTERM_COM "10006"
exit
;;

outstate)
ZTERM_COM "10007"
exit
;;


update-fw)
## Stop Serial Communication
rm -rfv /dev/zterm-tty
## Update Arduino over USB
FW_FILE="pwr-ctl"
rm -rf /opt/rpi/$FW_FILE/build
mkdir -p /opt/rpi/$FW_FILE/build
/opt/rpi/arduino-cli -v compile --fqbn arduino:avr:uno \
  /opt/rpi/$FW_FILE/$FW_FILE.ino --build-path /opt/rpi/$FW_FILE/build
/opt/rpi/arduino-cli -v upload -p /dev/$ARDUINO_PORT \
  --fqbn arduino:avr:uno --input-dir /opt/rpi/$FW_FILE/build
## Start amplifier communication
ln -sf /dev/$ARDUINO_PORT /dev/zterm-tty
ZTERM_COM "i"
exit
;;

*)
echo "Bedroom Controller - by Ben Provenzano III "
echo "Enter valid command."
exit 1
;;
esac   
