#!/bin/bash
###########################################################
## Main LEDgrid main script by Ben Provenzano III #########
###########################################################
###########################################################

case "$1" in

boot)
## Light Web Server
systemctl start lighttpd
## Unified Web Server
systemctl start rpi-urserver
## LED Controller
/opt/rpi/leds fc 40
sleep 4.25
/opt/rpi/leds stop
## Disable HDMI
/usr/bin/tvservice -o
## Auto Hotspot (on boot only)
sleep 60
systemctl start rpi-netdetect.service
exit
;;

	    
    *)
      echo "LEDgrid Server for Raspberry Pi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
