#!/bin/bash
###########################################################
## Main LEDgrid main script by Ben Provenzano III #########
###########################################################
###########################################################

case "$1" in

boot)
## Unified Web Server
systemctl start rpi-urserver
## LED Controller
/opt/rpi/leds fc 40
## Auto Hotspot (on boot only)
systemctl start rpi-netdetect.service
## Disable HDMI (saves 30mA)
/usr/bin/tvservice -o
## Turn-off Power LED (boot complete)
echo none | tee /sys/class/leds/led0/trigger
exit
;;

	    
    *)
      echo "LEDgrid Server for Raspberry Pi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
