#!/bin/bash
###########################################################
## Main LEDwall main script by Ben Provenzano III v7 ######
###########################################################
###########################################################

case "$1" in

boot)
## LED Controller
/opt/rpi/leds fc 40
## Light Web Server
systemctl start lighttpd
## Unified Web Server
systemctl start rpi-urserver
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

	    
    *)
      echo "LEDwall Server v6 for Raspberry Pi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
