#!/bin/bash
##### Attach/Detach ZFS Snapshots Share

if [ ! "$USER" = server ]; then
    echo "This script should only be ran by server user, aborting."
    exit 1
fi

read -p "Press (a) to attach ZFS snapshots, or enter to detach. " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Aa]$ ]]
then
  echo "Detaching share..."
  rm -f /mnt/backup/Snapshots
else
  echo ""
  if [ -e "/mnt/backup/Snapshots" ]; then
    echo "Already attached!"  	
  else
    echo "Attaching share..."
    ln -s /mnt/datastore/.zfs/snapshot /mnt/backup/Snapshots
  fi
fi
echo ""
exit