#!/bin/bash
### Run PVE script in screen terminal

SCRNVAR=$(echo $RANDOM)

if [ "$1" = "" ] ; then
  /usr/bin/screen -dm -t $SCRNVAR /usr/bin/svrutil.bin $1
  sleep 0.25
  screen -r -p $SCRNVAR
else
  /usr/bin/svrutil.bin $1
fi

exit