#!/bin/bash
################################
###### Proxmox VM Control ######
################################
################################

if [ ! "$USER" = server ]; then
  echo "This script should only be ran by server user, aborting."
  exit 1
fi

echo " "
echo "######################################"
echo "######## ProServer VM Utility ########"
echo "#### by Ben Provenzano III - v1.1 ####"
echo "######################################"
echo " "
echo "(l) Generate a server log"
echo "(x) Xana VM (start/stop)"
echo "(u) Unifi VM (start/stop)"
echo "(enter) exit utility"
echo " "

read -p "select a option: " -n 1 -r
echo

if [[ $REPLY =~ ^[Ll]$ ]]
then
touch /mnt/extbkps/keytmp/createlog.txt
echo ""
echo "Wait on-minute, server log will be written to."
echo "SMB: \\files\Downloads\Server.log"
echo ""
exit
fi

if [[ $REPLY =~ ^[Xx]$ ]]
then
VMHOST="xana"
fi

if [[ $REPLY =~ ^[Uu]$ ]]
then
VMHOST="unifi"
fi

if [[ ! $VMHOST = "" ]]
then
  echo ""
  read -p "select (b) to boot VM or (s) to shutdown VM: " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Bb]$ ]]
  then
   touch /mnt/extbkps/keytmp/start$VMHOST.txt
   echo "waiting one-minute for startup to trigger..."
   sleep 60
   cat /mnt/extbkps/keytmp/vmlog.txt
  fi
  if [[ $REPLY =~ ^[Ss]$ ]]
  then
   echo "stopping $VMHOST virtual machine..."
   ssh -t -i ~/ProOS/$VMHOST/id_rsa root@$VMHOST "shutdown -h now"
  fi
echo ""
fi

exit