#!/bin/bash
## Runs every 40 seconds on Proxmox
################################

ZFSPOOL1="usb256-01" # SanDisk Ultra 256GB USB 3.0
ZFSPOOL2="usb128-01" # SanDisk Ultra 128GB USB 3.0
ZFSPOOL3="usb128-02" # SanDisk Ultra 128GB USB 3.0
ZFSPOOL4="usb128-03" # SanDisk Cruzer 128GB USB 2.0
ZFSPOOL5="hdd4tb-01" # HGST 4GB Hard Drive (Oldest)
ZFSPOOL6="hdd4tb-02" # HGST 4GB Hard Drive (2017)
ZFSPOOL7="hdd4tb-03" # WD 4TB Blue Hard Drive (Newest)
ZFSPOOL8=""
ZFSPOOL9=""
ZFSPOOL10=""

### IMPORT ZFS ########################################   
if [ -e /mnt/extbkps/keytmp/pass.txt ]; then
###### Runs when file exists ##########################
  if [ ! -e /mnt/extbkps/keytmp/status.txt ]; then
    touch /mnt/extbkps/keytmp/status.txt
  else
    truncate -s 0 /mnt/extbkps/keytmp/status.txt
  fi
  echo ""
  for ((i=1; i<11; i++))
  do
  ZFSVAR0="ZFSPOOL$i"
    if [ "${!ZFSVAR0}" = "" ] || [ "${!ZFSVAR0}" = "datastore" ] || [ "${!ZFSVAR0}" = "tank" ] || [ "${!ZFSVAR0}" = "rpool" ] ; then
    echo "no pool specified."
    else
      echo "importing ZFS backup volume ${!ZFSVAR0}."
      zpool import ${!ZFSVAR0}
 	    zfs load-key -L file:///mnt/extbkps/keytmp/pass.txt ${!ZFSVAR0}/extbkp
	    zfs mount ${!ZFSVAR0}/extbkp
	    echo ""
    fi
  done
  echo ""
	zfs list
	echo ""
	zpool status
	echo ""
  shred -n 2 -z -u /mnt/extbkps/keytmp/pass.txt
  echo "imported ZFS backup volumes"
fi
### EXPORT ZFS ########################################
if [ -e /mnt/extbkps/keytmp/unmount.txt ]; then
###### Runs when file exists ##########################
  echo ""
  for ((i=1; i<11; i++))
  do
  ZFSVAR1="ZFSPOOL$i"
    if [ "${!ZFSVAR1}" = "" ] || [ "${!ZFSVAR1}" = "datastore" ] || [ "${!ZFSVAR1}" = "tank" ] || [ "${!ZFSVAR1}" = "rpool" ] ; then
    echo "no pool specified."
    else
      echo "unmounting ZFS backup volume ${!ZFSVAR1}."
      zfs unmount /mnt/extbkps/${!ZFSVAR1}
      zpool export ${!ZFSVAR1}
      echo ""
    fi
  done
  zfs unload-key -a
  echo ""
  zfs list
  echo ""
  zpool status
  echo ""
  rm -f /mnt/extbkps/keytmp/unmount.txt
  echo "unmounted ZFS backup volumes"
  date
  echo ""
fi

### START VMs #########################################   
if [ -e /mnt/extbkps/keytmp/startunifi.txt ]; then
###### Runs when file exists ##########################
  if [ ! -e /mnt/extbkps/keytmp/vmlog.txt ]; then
    touch /mnt/extbkps/keytmp/vmlog.txt
  else
    truncate -s 0 /mnt/extbkps/keytmp/vmlog.txt
  fi
  echo "Starting Unifi VM..." &>> /mnt/extbkps/keytmp/vmlog.txt
  qm start 102 &>> /mnt/extbkps/keytmp/vmlog.txt
  date &>> /mnt/extbkps/keytmp/vmlog.txt
  rm -f /mnt/extbkps/keytmp/startunifi.txt
fi
#######################################################
if [ -e /mnt/extbkps/keytmp/startxana.txt ]; then
###### Runs when file exists ##########################
  if [ ! -e /mnt/extbkps/keytmp/vmlog.txt ]; then
    touch /mnt/extbkps/keytmp/vmlog.txt
  else
    truncate -s 0 /mnt/extbkps/keytmp/vmlog.txt
  fi
  echo "Starting Xana VM..." &>> /mnt/extbkps/keytmp/vmlog.txt
  qm start 105 &>> /mnt/extbkps/keytmp/vmlog.txt
  date &>> /mnt/extbkps/keytmp/vmlog.txt
  rm -f /mnt/extbkps/keytmp/startxana.txt
fi

exit


