#!/bin/bash
###### Server VM Backup Script by Ben Provenzano III ######
###########################################################
###
echo ""
echo "Backing-up Files LXC 101..."
vzdump 101 --mode snapshot --compress 0 --node pve --storage local --maxfiles 1 --remove 1 --exclude-path /mnt/backup --exclude-path /mnt/extbkps
cp -v /etc/pve/lxc/101.conf /mnt/datastore/Ben/ProOS/pve/vmconfs/lxc-101.conf
chmod 777 /mnt/datastore/Ben/ProOS/pve/vmconfs/lxc-101.conf
###
echo ""
echo "Backing-up Plex LXC 104..."
vzdump 104 --mode snapshot --compress 0 --node pve --storage local --maxfiles 1 --remove 1 --exclude-path /mnt/transcoding
cp -v /etc/pve/lxc/104.conf /mnt/datastore/Ben/ProOS/pve/vmconfs/lxc-104.conf
chmod 777 /mnt/datastore/Ben/ProOS/pve/vmconfs/lxc-104.conf
###
echo ""
echo "Backing-up Router KVM 100..."
vzdump 100 --mode snapshot --compress lzo --node pve --storage local --maxfiles 1 --remove 1
cp -v /etc/pve/qemu-server/100.conf /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-100.conf
chmod 777 /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-100.conf
###
echo ""
echo "Backing-up Unifi KVM 102..."
vzdump 102 --mode snapshot --compress lzo --node pve --storage local --maxfiles 1 --remove 1
cp -v /etc/pve/qemu-server/102.conf /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-102.conf
chmod 777 /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-102.conf
###
echo ""
echo "Backing-up Xana KVM 105..."
echo "Only Xana configuration is backed up."
cp -v /etc/pve/qemu-server/105.conf /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-105.conf
chmod 777 /mnt/datastore/Ben/ProOS/pve/vmconfs/qemu-105.conf
###
echo ""
echo "Copying VM's to Datastore..."
cp -rv /var/lib/vz/dump/vzdump-* /mnt/datastore/Ben/ProOS/pve/vmbkps/
chmod -R 777 /mnt/datastore/Ben/ProOS/pve/vmbkps/vzdump-*
echo "Backup Complete."
echo ""
exit
