#!/bin/bash
###### System Check Script by Ben Provenzano III ##########
###########################################################
echo "*** Server Status ***"
/bin/date -R

echo ""
uptime

echo ""
uname -a
hostname

echo ""
echo "** Public IP **"
dig +short myip.opendns.com @resolver1.opendns.com

echo ""
echo "** Temperatures **"
/usr/bin/sensors -f coretemp-isa-0000
/usr/bin/sensors -f acpitz-acpi-0
/usr/bin/sensors -f nct6776-isa-0a30

echo "** Memory Usage **"
/usr/bin/free -m

echo ""
echo "** Internal Drives **"
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sda
/usr/sbin/hddtemp --unit=F /dev/sda
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sdb
/usr/sbin/hddtemp --unit=F /dev/sdb
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sdc
/usr/sbin/hddtemp --unit=F /dev/sdc
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sdd
/usr/sbin/hddtemp --unit=F /dev/sdd
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sde
/usr/sbin/hddtemp --unit=F /dev/sde
/usr/sbin/smartctl --all --quietmode=errorsonly /dev/sdf
/usr/sbin/hddtemp --unit=F /dev/sdf

echo ""
echo "** Drive Usage **"
df -h --type=zfs --type=ext4

echo ""
echo "** ZFS Drive Pools **"
/sbin/zpool status
/sbin/zpool list -v

echo ""
echo "** Top Processes **"
top -b -n 1  | head -n 15

echo ""
echo "** CPU Type **"
lscpu | grep -i Model
lscpu | grep -i "CPU(s)"
lscpu | grep -i MHz

echo ""
echo "** VM / LXC Status **"
/usr/sbin/pct list
echo ""
/usr/sbin/qm list


echo ""
echo "** UPS Battery Backup **"
/sbin/apcaccess status

echo ""
echo "** Network Statistics **"
ip -statistics address
echo ""
cat /proc/net/bonding/bond0

echo ""
echo "** Package Versions **"
pveversion --verbose

echo ""
echo "** PVE Storage Configuration **"
cat /etc/pve/storage.cfg

echo ""
exit 0
