#!/bin/bash
## Runs every 35 seconds
################################
#### External Drives Backup ####
################################
################################
## /usr/bin/screen -dmS zfs-extbkps -L -Logfile /mnt/extbkps/keytmp/status.txt /usr/bin/zfs-extbkps

ZFSPOOL1="usb256-01" # SanDisk Cruzer 256GB USB 3.0
ZFSPOOL2="usb128-01" # SanDisk Cruzer 128GB USB 3.0
ZFSPOOL3="usb128-02"
ZFSPOOL4="usb128-03" # SanDisk Cruzer 128GB USB 2.0
ZFSPOOL5="hdd4tb-01"
ZFSPOOL6="hdd4tb-02"
ZFSPOOL7="hdd4tb-03"
ZFSPOOL8=""
ZFSPOOL9=""
ZFSPOOL10=""

while true
do 
### WAIT ###
    sleep 35
### IMPORT ZFS ########################################   
    if [ ! -e /mnt/extbkps/keytmp/pass.txt ]; then
      echo ""  > /dev/null 2>&1
	  #echo "pass.txt not found"
	else
      if [ ! -e /mnt/extbkps/keytmp/status.txt ]; then
        touch /mnt/extbkps/keytmp/status.txt
      else
        truncate -s 0 /mnt/extbkps/keytmp/status.txt
      fi
      echo ""
      for ((i=1; i<11; i++))
      do
      ZFSVAR0="ZFSPOOL$i"
       if [ "${!ZFSVAR0}" = "" ] || [ "${!ZFSVAR0}" = "datastore" ] || [ "${!ZFSVAR0}" = "tank" ] || [ "${!ZFSVAR0}" = "rpool" ] ; then
        echo "no pool specified."
       else
       	echo "importing ZFS backup volume ${!ZFSVAR0}."
        zpool import ${!ZFSVAR0}
 	    zfs load-key -L file:///mnt/extbkps/keytmp/pass.txt ${!ZFSVAR0}/extbkp
	    zfs mount ${!ZFSVAR0}/extbkp
	    echo ""
       fi
      done
      echo ""
	  zfs list
	  echo ""
 	  shred -n 2 -z -u /mnt/extbkps/keytmp/pass.txt
  	  echo "imported ZFS backup volumes"
    fi
### EXPORT ZFS ########################################
    if [ ! -e /mnt/extbkps/keytmp/unmount.txt ]; then
      echo ""  > /dev/null 2>&1
      #echo "unmount.txt not found"
    else
      echo ""
      for ((i=1; i<11; i++))
      do
      ZFSVAR1="ZFSPOOL$i"
       if [ "${!ZFSVAR1}" = "" ] || [ "${!ZFSVAR1}" = "datastore" ] || [ "${!ZFSVAR1}" = "tank" ] || [ "${!ZFSVAR1}" = "rpool" ] ; then
        echo "no pool specified."
       else
       	echo "unmounting ZFS backup volume ${!ZFSVAR1}."
        zfs unmount /mnt/extbkps/${!ZFSVAR1}
        zpool export ${!ZFSVAR1}
        echo ""
       fi
      done
      zfs unload-key -a
      echo ""
      zfs list
      echo ""
      rm -f /mnt/extbkps/keytmp/unmount.txt
      echo "unmounted ZFS backup volumes"
      date
      echo ""
    fi
#######################################################    
done


