#!/bin/bash
### ONLY RUN ON THE SERVER!!
### AutoConfig - ProOS for Plex Container
### by Ben Provenzano III
###

## Add Plex Repo
if [ ! -e /etc/apt/sources.list.d/plexmediaserver.list ]; then
   echo deb https://downloads.plex.tv/repo/deb public main | tee /etc/apt/sources.list.d/plexmediaserver.list
   curl "https://downloads.plex.tv/plex-keys/PlexSign.key" | apt-key add -
fi

## Update Sources
apt-get --yes update

## Install Packages
apt-get install -y --no-upgrade --ignore-missing unzip wget rsync curl screen \
 parallel ethtool aptitude sudo gnupg iptables libdbus-1-dev libdbus-glib-1-dev \
 locales apt-transport-https plexmediaserver bpytop htop binutils

## Remove Packages
apt-get remove -y --purge shellinabox nginx-full nginx nginx-common

## Replace Process Monitor
ln -sf /usr/bin/bpytop /usr/bin/pytop

## Set Locale
if [ ! -e /etc/locales.generated ]; then
 dpkg-reconfigure locales
 touch /etc/locales.generated
fi

## Plex Service Configuration 
mkdir -p /etc/systemd/system/plexmediaserver.service.d
cp -r /tmp/config/override.conf /etc/systemd/system/plexmediaserver.service.d/
chmod 644 /etc/systemd/system/plexmediaserver.service.d/override.conf
chown root:root /etc/systemd/system/plexmediaserver.service.d/override.conf
systemctl disable plexmediaserver.service

## Auto SSH Login Key for root
mkdir -p /root/.ssh
cp -r /tmp/config/authorized_keys /root/.ssh/

## SSH Configuration
cp -r /tmp/config/sshd_config /etc/ssh
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

## Quiet Login 
touch /root/.hushlogin
chmod 644 /root/.hushlogin
chown root:root /root/.hushlogin

## Login Script
cp /tmp/config/profile /root/.profile
chown root:root /root/.profile
chmod +x /root/.profile

## System Configuration
cp -r /tmp/config/sysctl.conf /etc
chmod 644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf

## Logrotate Fix for LXCs
cp /tmp/config/logrotate.service /lib/systemd/system/
chmod 644 /lib/systemd/system/logrotate.service
chown root:root /lib/systemd/system/logrotate.service

## Startup Configuration
cp -r /tmp/config/rc-local.service /etc/systemd/system/
chmod 644 /etc/systemd/system/rc-local.service
chown root:root /etc/systemd/system/rc-local.service
cp -r /tmp/config/rc.local /etc/
chmod 755 /etc/rc.local
chown root:root /etc/rc.local
systemctl enable rc-local

## Clean-up
systemctl daemon-reload
rm -r /tmp/config/
apt-get clean -y
apt-get autoclean -y
exit
