#!/bin/bash
##

# Import Host Name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

OSVER="$(sed -n 's|^VERSION=".*(\(.*\))"|\1|p' /etc/os-release)"

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
touch /boot/firmware/apd.enable
cp -f $BIN/modconf/cmdline.txt /boot/firmware/
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Larger Console Font
cp -f $BIN/modconf/console-setup /etc/default/
chmod 644 /etc/default/console-setup
chown root:root /etc/default/console-setup
service console-setup restart

## Access Point
cp -rv $BIN/modconf/hostapd.conf /etc/hostapd/hostapd.conf
chmod 644 /etc/hostapd/hostapd.conf
chown root:root /etc/hostapd/hostapd.conf

## Start Emulationstation on Boot
cp -rv $BIN/modconf/bashrc /home/pi/.bashrc
chmod +x /home/pi/.bashrc
chown pi:pi /home/pi/.bashrc

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

exit
