#!/bin/bash
## Cameras Pi Configuration Setup Script v6.0
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Google Drive Support
rm -f /root/.config/rclone/rclone.conf
if [ ! -e /media/usb0/rclone/rclone.conf ]; then
  echo "API key not found on flash drive, running setup..."
  echo "Create new remote named 'gsync' and attach to Google Drive"
  rclone config
  mkdir -p /media/usb0/rclone
  cp -fv /root/.config/rclone/rclone.conf /media/usb0/rclone/
  cat /media/usb0/rclone/rclone.conf
  chmod -R 777 /media/usb0/rclone
fi

## Camera Motion Configuration 
cp -f $BIN/modconf/motion.conf /etc/motion/
chmod 644 /etc/motion/motion.conf
chown root:root /etc/motion/motion.conf
cp -fr $BIN/modconf/camera*.conf /etc/motion/
chmod -R 644 /etc/motion/camera*.conf
chown -R root:root /etc/motion/camera*.conf

## Cameras USB Drive
if [ ! -e /media/usb0/cameras ]; then
  echo "Cameras folder on USB drive not found, creating..."
  mkdir -p /media/usb0/cameras
  chown -R motion:motion /media/usb0/cameras
fi

## Pi and Motion Permissions
rm -f /etc/sudoers.d/010_pi-perms
rm -f /etc/sudoers.d/010_pi-nopasswd
sh -c "touch /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"motion ALL=(ALL) NOPASSWD:/opt/rpi/main*\" >> /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"pi ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers.d/010_pi-nopasswd"
chown root:root /etc/sudoers.d/010_pi-nopasswd
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/010_pi-nopasswd
chmod u=r,g=r,o= /etc/sudoers.d/010_pi-nopasswd

## Camera IR Control
cp -f $BIN/modconf/rpi-ldr.service /etc/systemd/system/
chmod -f 644 /etc/systemd/system/rpi-ldr.service
chown -f root:root /etc/systemd/system/rpi-ldr.service

## Custom Port Redirection
cp -f $BIN/modconf/lighttpd.conf /etc/lighttpd/
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf

## AutoFS Configuration
cp -f $BIN/modconf/auto.master /etc/
chmod 644 /etc/auto.master
chown root:root /etc/auto.master
cp -f $BIN/modconf/auto.map /etc/
chmod 644 /etc/auto.map
chown root:root /etc/auto.map
cp -f $BIN/modconf/auto.creds /etc/
chmod 400 /etc/auto.creds
chown root:root /etc/auto.creds
mkdir -p /mnt/smb

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main
ln -sf /opt/rpi/camcleanup /usr/bin/camcleanup

exit
