#!/bin/bash
##
## CameraPi by Ben Provenzano III v1.5 #############
####################################################
case "$1" in

boot)
## Video RAM Disk
mkdir -p /mnt/ramdisk
chmod 777 /mnt/ramdisk
mount -t tmpfs -o size=200m ramdisk /mnt/ramdisk
sleep 25
## Attach Server SMB Share
if ping -c 1 10.177.1.4 > /dev/null 2> /dev/null
then
  systemctl start autofs
  sleep 5.75
fi
## Google Drive
if [ ! -e /media/usb0/rclone ]; then
  echo "Flash drive not connected, not starting rclone."
else
  systemctl start rpi-rclone
  sleep 5.75
fi
## Motion Server
systemctl start motion
## Cameras Cleanup Timer
systemctl start rpi-camcleanup.timer
## IR Control
systemctl start rpi-ldr.service
## Disable HDMI
/usr/bin/tvservice -o
exit
;;

ircutoff)
## Disable IR Filter (GPIO #17)
gpio mode 0 out
gpio write 0 1
exit
;;

ircuton)
## Enable IR Filter (GPIO #17)
gpio mode 0 out
gpio write 0 0
exit
;;

iroff)
## Disable IR LEDs (GPIO #27)
gpio mode 2 out
gpio write 2 0
exit
;;

iron)
## Enable IR LEDs (GPIO #27)
gpio mode 2 out
gpio write 2 1
exit
;;

redoff)
## Disable Red LED
echo 1 | tee /sys/class/leds/led1/brightness > /dev/null 2> /dev/null
exit
;;

redon)
## Enable Red LED
echo 0 | tee /sys/class/leds/led1/brightness > /dev/null 2> /dev/null
exit
;;

    
        *)
	      echo "  Cameras v1"
	      echo "  by Ben Provenzano III"
	      echo " "
	      echo "Enter a valid command line argument."
          exit 1
        ;;
    esac   
