#!/bin/bash
##
##################################

case "$1" in

boot)
## Motion Server
systemctl start rpi-motion.service
exit
;;


##################################
    
    *)
	    echo "enter a valid command argument."
        exit 1
    ;;
    esac   
