#!/bin/bash
##
## Portable Pi Zero Speaker by Ben Provenzano III v2.2 #########
################################################################

## Read the 1st Argument
case "$1" in

boot)
## Pop Eliminator
/usr/bin/amixer set PCM 0%
sleep 1.25
systemctl start rpi-zeroaudio
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## AirPlay Support
systemctl start nqptp
systemctl start rpi-airplay
## Startup Sound / Set Volume
/usr/bin/amixer set PCM 60%
/usr/bin/aplay /opt/rpi/sounds/ds.wav
sleep 1.25
/usr/bin/amixer set PCM 99%
## Reset Bluetooth Connections
/opt/rpi/init resetbt
## Auto Hotspot (on boot only)
# only run if bluetooth not connected
if [ ! -e /tmp/bt.connected ]; then
   systemctl start rpi-netdetect.service
fi
## Disable HDMI (saves 30mA)
tvservice -o
exit
;;

vup)
## Volume Up
/usr/bin/amixer set PCM 2%+
exit
;;

vdwn)
## Volume Down
/usr/bin/amixer set PCM 2%-
exit
;;

### Examples of URL strings ###
# http://automate:9300/exec.php?var=&arg=lightson&action=main
# http://automate:9300/exec.php?var=&arg=lightsoff&action=main
# http://automate:9300/exec.php?var=prism&arg=video&action=leds
###############################


    
        *)
	      echo "  AirPi Portable"
	      echo "  by Ben Provenzano III"
	      echo " "
	      echo "Enter a valid command line argument."
        exit 1
        ;;
    esac   
