#!/bin/bash
if [[ ! $NAME =~ ^\"([0-9A-F]{2}[:-]){5}([0-9A-F]{2})\"$ ]]; then exit 0; fi
action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")
if [ "$action" = "add" ]; then
    bluetoothctl discoverable off
    # disconnect wifi to prevent dropouts
    ifconfig wlan0 down &
fi
if [ "$action" = "remove" ]; then
    # reenable wifi
    ifconfig wlan0 up &
    bluetoothctl discoverable on
fi