#!/bin/bash
# /etc/preinit by Ben Provenzano III
# Ran on boot, do not change this starts the network

#### Network Startup ###############################
/usr/bin/screen -dm /bin/bash /etc/netmode.sh client || :

## Sync Local Clock
sleep 5.25
systemctl start systemd-timesyncd

#### Cleanup Timer ################################

systemctl start rpi-cleanup.timer

#### Module Startup ###############################

## Start Modules
if [ ! -e /opt/rpi/main ]; then
   echo "Module boot script not found."
else
   echo "Starting module boot script..."
   /opt/rpi/main boot
fi
exit
