#!/bin/sh
## System Configuration Script v6.0
## Bedroom Pi

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -fv $BIN/modconf/config.txt /boot/firmware/
## Access Point Config
cp -fv $BIN/modconf/apd.conf /boot/firmware/
## Disable Wi-Fi on Boot
touch /boot/firmware/disable.wifi
## Open Access Point Mode with MAC Filtering
touch /boot/firmware/apd-open.mode
mount -o remount,ro /boot/firmware

## ALSA Configuration
cp -f $BIN/modconf/asound.conf /etc/
chmod 644 /etc/asound.conf
chown root:root /etc/asound.conf

## Samba / AppleTalk password
SHRPASS="ben1995"

## Ben user configuration
SHRUSER1="ben"
groupadd -g 1015 shared
useradd "$SHRUSER1" --password='' --shell=/bin/false
passwd ${SHRUSER1} << EOD
${SHRPASS}
${SHRPASS}
EOD
smbpasswd -a -s ${SHRUSER1} << EOD
${SHRPASS}
${SHRPASS}
EOD
usermod -a -G shared ${SHRUSER1}  

## Media user configuration
SHRUSER2="media"
useradd "$SHRUSER2" --password='' --shell=/bin/false
passwd ${SHRUSER2} << EOD
${SHRPASS}
${SHRPASS}
EOD
smbpasswd -a -s ${SHRUSER2} << EOD
${SHRPASS}
${SHRPASS}
EOD
usermod -a -G shared ${SHRUSER2}  

## AutoFS configuration
cp -f $BIN/modconf/auto.master /etc/
chmod 644 /etc/auto.master
chown root:root /etc/auto.master
cp -f $BIN/modconf/auto.map /etc/
chmod 644 /etc/auto.map
chown root:root /etc/auto.map
cp -f $BIN/modconf/auto.creds /etc/
chmod 400 /etc/auto.creds
chown root:root /etc/auto.creds
mkdir -p /mnt/smb

## Samba configuration 
cp -f $BIN/modconf/smb.conf /etc/samba/
chmod 644 /etc/samba/smb.conf
chown root:root /etc/samba/smb.conf

## AppleTalk configuration
cp -f $BIN/modconf/afp.conf /etc/netatalk/
chmod 644 /etc/netatalk/afp.conf 
chown root:root /etc/netatalk/afp.conf

## Arduino configuration
/opt/rpi/arduino-cli core install arduino:avr
/opt/rpi/arduino-cli lib install Encoder@1.4.4

## Link main script
ln -sf /opt/rpi/main /usr/bin/main

exit
