#!/bin/bash
###########################################################
####### Motion copy script by Ben Provenzano III v2 #######
###########################################################

## File Share IP
SERVERIP=10.177.1.4

## Read camera name
VARA=$1
## Read file name
VARB=$2

## Test file names
#touch /tmp/motioncam.log
#echo "$VARA" | tee -a /tmp/motioncam.log
#touch /tmp/motionfile.log
#echo "$VARB" | tee -a /tmp/motionfile.log

########################################################
if ! ping -c 1 $SERVERIP > /dev/null 2> /dev/null; then
  echo "Server not connected."
  if [ ! -e /mnt/gsync/Current ]; then
    echo "Google Drive and server not connected."
    if [ ! -e /media/usb0/cameras ]; then
      echo "Flash drive not connected, discarding video."
    else
      #echo "Copying to Flash drive..."
      mkdir -p /media/usb0/cameras/$VARA
      cp -f $VARB.mp4 /media/usb0/cameras/$VARA/
    fi
  else
    #echo "Copying to Google Drive..."
    mkdir -p /mnt/gsync/Current/$VARA
    cp -f $VARB.mp4 /mnt/gsync/Current/$VARA/
  fi
else
  #echo "Copying to Server..."	
  mkdir -p /mnt/smb/Cameras/Current/$VARA
  cp -f $VARB.mp4 /mnt/smb/Cameras/Current/$VARA/
  ################################################
  if [ ! -e /mnt/gsync/Current ]; then
    echo "Google Drive not connected."
  else
    #echo "Copying to Google Drive..."
    mkdir -p /mnt/gsync/Current/$VARA
    cp -f $VARB.mp4 /mnt/gsync/Current/$VARA/
  fi
fi

## Delete video from RAM Disk
rm -f $VARB.mp4

## Turn off status LED
/usr/bin/sudo /opt/rpi/main redoff

exit