#!/bin/sh
## AirZero II Configuration Script v7.0

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
mount -o remount,ro /boot

## ALSA Configuration
cp -f $BIN/modconf/asound.conf /etc
chmod 644 /etc/asound.conf
chown root:root /etc/asound.conf

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

## Routed Hotspot Configuration
#cp -f /etc/dnsmasq.routed /etc/dnsmasq.conf
#chmod 644 /etc/dnsmasq.conf
#chown root:root /etc/dnsmasq.conf

exit
