#!/bin/bash
###########################################################

## Read the 2nd Argument
ARG2=$2

## Read the 1st Argument
case "$1" in

boot)
## AirPlay Support
OSVER="$(sed -n 's|^VERSION=".*(\(.*\))"|\1|p' /etc/os-release)"
if [ "${OSVER}" = "bullseye" ]; then
  systemctl start nqptp
fi
systemctl start rpi-airplay
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## Disable HDMI (saves 30mA)
tvservice -o
## Auto Hotspot
systemctl start rpi-netdetect
exit
;;

relax)
## Play sound in loop
systemctl stop rpi-relaxloop
systemctl set-environment rpi_relaxmode=$ARG2
systemctl start rpi-relaxloop
exit
;;

stoprelax)
systemctl stop rpi-relaxloop
exit
;;



        *)
          echo "HiFi System"
	      echo "  by Ben Provenzano III "
          exit 1
          ;;
    esac   
