#!/bin/sh
## AirZero II Configuration Script v7.0

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
mount -o remount,ro /boot

## lighttpd Configuration
cp -f $BIN/modconf/lighttpd.conf /etc/lighttpd/
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf

## ALSA Configuration
cp -f $BIN/modconf/asound.conf /etc
chmod 644 /etc/asound.conf
chown root:root /etc/asound.conf

## Install Remotes
cp -r $BIN/modconf/remotes/* /opt/rpi/remotes/

## Stage II - Set module name to configs
if [ ! -e $BIN/modconf/brand.txt ]; then
echo "Skip module naming."
else
echo "Setting module name."
## Set module name to unified server
sed -i "s/RaspberryPi/$MODNAME/g" /opt/rpi/manager/client.html
sed -i "s/raspberrypi/$HOSTNAME/g" /opt/rpi/manager/client.html
fi

## AutoFS Configuration
cp -f $BIN/modconf/auto.master /etc/
chmod 644 /etc/auto.master
chown root:root /etc/auto.master
cp -f $BIN/modconf/auto.map /etc/
chmod 644 /etc/auto.map
chown root:root /etc/auto.map
mkdir -p /mnt/smb

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

## Routed Hotspot Configuration
#cp -f /etc/dnsmasq.routed /etc/dnsmasq.conf
#chmod 644 /etc/dnsmasq.conf
#chown root:root /etc/dnsmasq.conf

## Change Web Server Default Theme
/opt/rpi/init dpurple

exit
