#!/bin/bash
## Cameras Pi Configuration Setup Script v1.0
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Pi Camera Python Library
apt install -y python3-picamera2 python3-simplejpeg --no-install-recommends
usermod -a -G video root

## Pi and Motion Permissions
rm -f /etc/sudoers.d/010_pi-perms
rm -f /etc/sudoers.d/010_pi-nopasswd
sh -c "touch /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"motion ALL=(ALL) NOPASSWD:/opt/rpi/main*\" >> /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"pi ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers.d/010_pi-nopasswd"
chown root:root /etc/sudoers.d/010_pi-nopasswd
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/010_pi-nopasswd
chmod u=r,g=r,o= /etc/sudoers.d/010_pi-nopasswd

## Allow Password Login
cp -fv $BIN/modconf/sshd_config /etc/ssh/
chown root:root /etc/ssh/sshd_config
chmod 644 /etc/ssh/sshd_config

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

exit
