#!/bin/bash
## Cameras Pi Configuration Setup Script v1.0
##

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Module Path
BIN=/opt/rpi
# Import Module Name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Camera Motion Configuration 
cp -f $BIN/modconf/motion.conf /etc/motion/
chmod 644 /etc/motion/motion.conf
chown root:root /etc/motion/motion.conf
cp -fr $BIN/modconf/camera*.conf /etc/motion/
chmod -R 644 /etc/motion/camera*.conf
chown -R root:root /etc/motion/camera*.conf

## Pi and Motion Permissions
rm -f /etc/sudoers.d/010_pi-perms
rm -f /etc/sudoers.d/010_pi-nopasswd
sh -c "touch /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"motion ALL=(ALL) NOPASSWD:/opt/rpi/main*\" >> /etc/sudoers.d/010_pi-nopasswd"
sh -c "echo \"pi ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers.d/010_pi-nopasswd"
chown root:root /etc/sudoers.d/010_pi-nopasswd
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/010_pi-nopasswd
chmod u=r,g=r,o= /etc/sudoers.d/010_pi-nopasswd

## Custom Port Redirection
cp -f $BIN/modconf/lighttpd.conf /etc/lighttpd/
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main

exit
