#!/bin/bash
###########################################################

## Read the 1st Argument
case "$1" in

boot)
## AirPlay Support
systemctl start rpi-airplay
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## Auto Hotspot
systemctl start rpi-netdetect
exit
;;


*)
echo "Hi-Fi System"
echo "by Ben Provenzano III "
exit 1
;;
esac   
