#!/bin/bash
## LCDpi API by Ben Provenzano III

DELAYSET(){ 
echo "${SIG}d${ARG}" > /dev/zterm
}

ERASELCD(){ 
echo "${SIG}c3" > /dev/zterm
}

## Message File Path
MSG_PATH="/var/www/html/ram/message"

## Control Mode
SIG='$?-|'

CMD="$1"
ARG="$2"

case "$CMD" in

boot)
## Start Z-Terminal Service
systemctl stop serial-getty@ttyS0
ln -sf /dev/ttyS0 /dev/zterm-tty
systemctl start rpi-ztermcom
## Initialize Message Service
rm -rfv "$MSG_PATH*.txt"
touch /var/www/html/ram/message.txt
chmod 777 /var/www/html/ram/message.txt
chown www-data:www-data /var/www/html/ram/message.txt
## Turn off power LED
echo 0 > /sys/class/leds/ACT/brightness
## Set Default Character Delay
ARG="250"
DELAYSET
sleep 1
## Erase Display
ERASELCD
exit
;;

restart)
systemctl restart ztermcom
exit
;;

weather)
/usr/bin/inxi -xxxW 42.882698,-78.876442 \
 --weather-unit i --no-ssl \
 | sed 's/Report://g; 
   s/conditions: //g;
   s\ temperature:\temp:\g; 
   s\Weather:\Buffalo, NY\g' \
 | tr -s ' ' > /tmp/weather.raw
tr -d '\n' < /tmp/weather.raw > /tmp/weather.txt
ex -sc '%s/\(\pressure:\).*/\1/ | x' /tmp/weather.txt
sed -i 's/pressure://g' /tmp/weather.txt
## Send Message
WEATHER=$(cat /tmp/weather.txt)
echo "$WEATHER" > /dev/zterm
exit
;;

message)
## add space to EOF
echo ' ' >> "$MSG_PATH.txt"
## rotate archived messages
for i in {5..1}
do
   mv -f "$MSG_PATH-$i.txt" "$MSG_PATH-$((i+1)).txt"
done
mv -f "$MSG_PATH.txt" "$MSG_PATH-1.txt"
cat "$MSG_PATH-1.txt" > /dev/zterm
exit
;;

msgarchive)
cat "$MSG_PATH-$ARG.txt" > /dev/zterm
exit
;;

delay)
DELAYSET
exit
;;

backlight)
echo "${SIG}b${ARG}" > /dev/zterm
exit
;;

lorem)
cat /opt/rpi/lorem_ipsum.txt > /dev/zterm
exit
;;

erase)
ERASELCD
exit
;;

erase-btm)
echo "${SIG}c2" > /dev/zterm
exit
;;

erase-top)
echo "${SIG}c1" > /dev/zterm
exit 
;;

stop)
echo "${SIG}c0" > /dev/zterm
exit
;;
    
*)
  exit 1
;;
esac   
