#!/bin/bash
## Main Parser

DELAYSET(){ 
echo "${SIG}d${ARG}" > /dev/zterm
}

CLEARLCD(){ 
echo "${SIG}c3" > /dev/zterm
}

SIG='$?-|'

ARG="$2"

case "$1" in

boot)
## Start Z-Terminal Service
systemctl stop serial-getty@ttyS0
sleep 1.5
systemctl start ztermcom
## Delete messages
rm -rfv /tmp/message*.txt
## Turn off power LED
echo 0 > /sys/class/leds/ACT/brightness
## Disable HDMI (saves 30mA)
tvservice -o
## Set Default Character Delay
ARG="300"
DELAYSET
sleep 1
## Clear Display
CLEARLCD
exit
;;

restart)
systemctl restart ztermcom
exit
;;

weather)
/usr/bin/inxi -xxxW 42.882698,-78.876442 \
 --weather-unit i --no-ssl \
 | sed 's/Report://g; 
   s/conditions: //g;
   s\ temperature:\temp:\g; 
   s\Weather:\Buffalo, NY\g' \
 | tr -s ' ' > /tmp/weather.raw
tr -d '\n' < /tmp/weather.raw > /tmp/weather.txt
ex -sc '%s/\(\pressure:\).*/\1/ | x' /tmp/weather.txt
sed -i 's/pressure://g' /tmp/weather.txt
## Send Message
curl -X POST 127.0.0.1/upload.php \
 -H "Content-Type: text/plain" -d "$(cat /tmp/weather.txt)"
exit
;;

message)
## add space to EOF
echo ' ' >> /tmp/message.txt
## retain archived messages
for i in {5..1}
do
   mv -f /tmp/message-$i.txt /tmp/message-$((i+1)).txt
done
mv -f /tmp/message.txt /tmp/message-1.txt
cat /tmp/message-1.txt > /dev/zterm
exit
;;

msgarchive)
cat /tmp/message-$ARG.txt > /dev/zterm
exit
;;

delay)
DELAYSET
exit
;;

backlight)
echo "${SIG}b${ARG}" > /dev/zterm
exit
;;

clear)
CLEARLCD
exit
;;

clear-btm)
echo "${SIG}c2" > /dev/zterm
exit
;;

clear-top)
echo "${SIG}c1" > /dev/zterm
exit 
;;

lorem)
cat /opt/rpi/lorem_ipsum.txt > /dev/zterm
exit
;;

stop)
echo "${SIG}c0" > /dev/zterm
exit
;;
    
*)
  exit 1
;;
esac   
