#!/bin/sh
## Hi-Fi Pi Configuration Script

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e "/opt/rpi/init" ]; then
  echo "Core components missing or corrupted."
  echo "Exiting..."
  exit
fi
echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -f $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## ALSA Configuration
cp -f $BIN/modconf/asound.conf /etc/
chmod 644 /etc/asound.conf
chown root:root /etc/asound.conf

exit
