#!/bin/sh
export DISPLAY=":1"
APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
nice -n 10 /opt/rpi/java/bin/java -Xss128k -Xmx128m -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/SpectroGraph.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/mp3spi1.9.5.jar:$APPDIR/lib/jl1.0.1.jar:$APPDIR/lib/jsminim.jar" SpectroGraph "$@"
exit 0
