#!/bin/bash
### ONLY RUN ON THE SERVER!!
### AutoConfig - ProOS for Files Container
### by Ben Provenzano III
###

## Update Sources
apt-get --yes update

## Install Packages
apt-get install -y --no-upgrade --ignore-missing unzip wget \
 rsync curl screen scrub ethtool aptitude sudo samba sshpass \
 libdbus-1-dev libdbus-glib-1-dev bc git locales mailutils \
 neofetch apt-transport-https nmap bpytop htop binutils

## Process Monitor Symlink
ln -sf /usr/bin/bpytop /usr/bin/pytop

## Set Locale
if [ ! -e /etc/locales.generated ]; then
  dpkg-reconfigure locales
  touch /etc/locales.generated
fi

## SSH key for root user
mkdir -p /root/.ssh
cp /tmp/config/authorized_keys /root/.ssh/
chown root:root /root/.ssh/authorized_keys
chmod 644 /root/.ssh/authorized_keys

## SSH key for server user
if [ ! -e /home/server ]; then
  echo "Creating Server Home Directory..."
  mkdir -p /home/server
  mkdir -p /home/server/.ssh
  chown -R server:server /home/server
fi
cp /tmp/config/authorized_keys.server /home/server/.ssh/authorized_keys
chmod 644 /home/server/.ssh/authorized_keys
chown server:server /home/server/.ssh/authorized_keys
touch /home/server/.hushlogin
chmod 644 /home/server/.hushlogin
chown server:server /home/server/.hushlogin

## Regions Shared Folder
if [ ! -e /home/server/.regions ]; then
  mkdir -p /home/server/.regions
  chown server:server /home/server/.regions
  chmod 755 /home/server/.regions
fi

## User Symlinks
if [ ! -e "/home/server/ProOS" ]; then
  ln -s /mnt/ben/ProOS /home/server/ProOS
fi
if [ ! -e "/home/server/Downloads" ]; then
  ln -s /mnt/scratch/downloads /home/server/Downloads
fi

## Server Login Script
cp /tmp/config/profile.server /home/server/.profile
chown server:server /home/server/.profile
chmod +x /home/server/.profile

## Server Login Script
cp /tmp/config/git.config /home/server/.gitconfig
chown server:server /home/server/.gitconfig
chmod 600 /home/server/.gitconfig

## Remove Passwords
passwd -d root
passwd -d server

## SSH Configuration
cp /tmp/config/sshd_config /etc/ssh
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

## System Configuration
cp /tmp/config/sysctl.conf /etc
chmod 644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf

## Logrotate Fix for LXCs
cp /tmp/config/logrotate.service /lib/systemd/system/
chmod 644 /lib/systemd/system/logrotate.service
chown root:root /lib/systemd/system/logrotate.service

## Startup Configuration
cp /tmp/config/rc-local.service /etc/systemd/system/
chmod 644 /etc/systemd/system/rc-local.service
chown root:root /etc/systemd/system/rc-local.service
cp /tmp/config/rc.local /etc/
chmod 755 /etc/rc.local
chown root:root /etc/rc.local
systemctl enable rc-local

## Main Cron Timer
cp /tmp/config/rootcron /etc/cron.d/
chmod 644 /etc/cron.d/rootcron
chown root:root /etc/cron.d/rootcron
systemctl restart cron

## Supress Slice Log Entries
cp /tmp/config/ignore-session-slice.conf /etc/rsyslog.d/
chmod 644 /etc/rsyslog.d/ignore-session-slice.conf
chown root:root /etc/rsyslog.d/ignore-session-slice.conf
systemctl restart rsyslog

## Backup Script
cp /tmp/config/svrbackup.sh /usr/bin/
chmod 755 /usr/bin/svrbackup.sh
chown root:root /usr/bin/svrbackup.sh

## Camera Cleanup Script
cp /tmp/config/camcleanup /usr/bin/
chmod 755 /usr/bin/camcleanup
chown root:root /usr/bin/camcleanup

## Samba Configuration
cp /tmp/config/smb.conf /etc/samba
chmod 644 /etc/samba/smb.conf
chown root:root /etc/samba/smb.conf

## Light Web Server
apt-get install -y --no-upgrade lighttpd
apt-get install -y --no-upgrade php-common php-cgi php php-mysql
## LightTPD Configuration
cp -f /tmp/config/lighttpd.conf /etc/lighttpd
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf
lighttpd-enable-mod fastcgi fastcgi-php; lighty-enable-mod fastcgi-php
ln -sf /etc/lighttpd/conf-available/10-fastcgi.conf /etc/lighttpd/conf-enabled/
ln -sf /etc/lighttpd/conf-available/15-fastcgi-php.conf
ln -sf /usr/share/lighttpd/create-mime.conf.pl /usr/share/lighttpd/create-mime.assign.pl
systemctl disable lighttpd
systemctl restart lighttpd

## PHP Configuration
PHP_VERSION=$(php -v | tac -r | tail -n 1 | cut -d " " -f 2 | cut -c 1-3)
cp -rf /tmp/config/php.cgi.ini /etc/php/$PHP_VERSION/cgi/php.ini
chmod 644 /etc/php/$PHP_VERSION/cgi/php.ini
chown root:root /etc/php/$PHP_VERSION/cgi/php.ini
cp -rf /tmp/config/php.cli.ini /etc/php/$PHP_VERSION/cli/php.ini
chmod 644 /etc/php/$PHP_VERSION/cli/php.ini
chown root:root /etc/php/$PHP_VERSION/cli/php.ini
chown -R www-data:www-data /var/lib/php
chmod -R g+rx /var/lib/php
if [ -e /lib/systemd/system/phpsessionclean.service ]; then
  systemctl disable phpsessionclean.timer
  systemctl disable phpsessionclean.service
  rm -f /lib/systemd/system/phpsessionclean.timer
  rm -f /lib/systemd/system/phpsessionclean.service
fi

## Base website files
mkdir -p /var/www/sessions
chmod -R g+rx /var/www/sessions
chown -R www-data:www-data /var/www/sessions
mkdir -p /var/www/uploads
chmod -R g+rx /var/www/uploads
chown -R www-data:www-data /var/www/uploads

## WWW Permissions allow running as server user
rm -f /etc/sudoers.d/www-perms
sh -c "touch /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(server) NOPASSWD:/usr/bin/wwwcmds\" >> /etc/sudoers.d/www-perms"
chown root:root /etc/sudoers.d/www-perms
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/www-perms
chmod u=r,g=r,o= /etc/sudoers.d/www-perms
rm -f /etc/sudoers.d/nobody-perms

### WWW Shell Commands
cp -f /tmp/config/wwwcmds.sh /usr/bin/wwwcmds.run
chmod +x /usr/bin/wwwcmds.run
chown root:root /usr/bin/wwwcmds.run
cp -f /tmp/config/wwwrun.sh /usr/bin/wwwcmds
chmod +x /usr/bin/wwwcmds
chown root:root /usr/bin/wwwcmds

## Clean-up
rm -f /usr/bin/svrbackup.bin
rm -f /mnt/extbkps/drives.txt
rm -f /usr/bin/svrutil.bin
systemctl daemon-reload
rm -r /tmp/config/
apt-get autoremove -y
sleep 2.5
apt-get autoclean -y
exit
