#!/bin/bash
### ONLY RUN ON THE SERVER!!
### AutoConfig - ProOS for Files Container
### by Ben Provenzano III
###

## Update Sources
apt-get --yes update

## Install Packages
apt-get install -y --no-upgrade --ignore-missing unzip wget \
 rsync curl screen scrub ethtool aptitude sudo samba sshpass \
 libdbus-1-dev libdbus-glib-1-dev bc git locales mailutils \
 neofetch apt-transport-https nmap bpytop htop binutils iperf3

## Process Monitor Symlink
ln -sf /usr/bin/bpytop /usr/bin/pytop

## Set Locale
if [ ! -e /etc/locales.generated ]; then
  dpkg-reconfigure locales
  touch /etc/locales.generated
fi

## SSH key for root user
mkdir -p /root/.ssh
cp /tmp/config/authorized_keys /root/.ssh/
chown root:root /root/.ssh/authorized_keys
chmod 644 /root/.ssh/authorized_keys

## SSH key for server user
if [ ! -e /home/server ]; then
  echo "Creating Server Home Directory..."
  mkdir -p /home/server
  mkdir -p /home/server/.ssh
  chown -R server:server /home/server
fi
cp /tmp/config/authorized_keys.server /home/server/.ssh/authorized_keys
chmod 644 /home/server/.ssh/authorized_keys
chown server:server /home/server/.ssh/authorized_keys
touch /home/server/.hushlogin
chmod 644 /home/server/.hushlogin
chown server:server /home/server/.hushlogin

## Regions Shared Folder
if [ ! -e /home/server/.regions ]; then
  mkdir -p /home/server/.regions
  chown server:server /home/server/.regions
  chmod g+rx /home/server/.regions
fi

## User Symlinks
if [ ! -e "/home/server/ProOS" ]; then
  ln -s /mnt/ben/ProOS /home/server/ProOS
fi
if [ ! -e "/home/server/Downloads" ]; then
  ln -s /mnt/scratch/downloads /home/server/Downloads
fi

## LightTPD Web Server
apt-get install -y --no-upgrade lighttpd php-cgi php php-common
cp -f /tmp/config/lighttpd.conf /etc/lighttpd
chmod 644 /etc/lighttpd/lighttpd.conf
chown root:root /etc/lighttpd/lighttpd.conf
lighttpd-enable-mod fastcgi fastcgi-php
lighty-enable-mod fastcgi-php
systemctl disable lighttpd
systemctl restart lighttpd

## Base website files
rm -rvf /var/www/html
mkdir -p /var/www/sessions
chmod -R g+rx /var/www/sessions
chown -R www-data:www-data /var/www/sessions
mkdir -p /var/www/uploads
chmod -R g+rx /var/www/uploads
chown -R www-data:www-data /var/www/uploads
if [ ! -e /home/server/.html ]; then
  mkdir -p /home/server/.html
  chown www-data:www-data /home/server/.html
  chmod g+rx /home/server/.html
fi

## Link external resources to web server
cp -f /tmp/config/exec.php /home/server/.html/
chmod +x /home/server/.html/exec.php
chown root:root /home/server/.html/exec.php

## WWW Permissions allow running as server user
rm -f /etc/sudoers.d/www-perms
sh -c "touch /etc/sudoers.d/www-perms"
sh -c "echo \"www-data ALL=(server) NOPASSWD:/usr/bin/wwwrun\" >> /etc/sudoers.d/www-perms"
chown root:root /etc/sudoers.d/www-perms
chmod u=rwx,g=rx,o=rx /etc/sudoers.d/www-perms
chmod u=r,g=r,o= /etc/sudoers.d/www-perms
rm -f /etc/sudoers.d/nobody-perms

### WWW Shell Commands
cp -f /tmp/config/www.sh /usr/bin/
chmod +x /usr/bin/www.sh
chown root:root /usr/bin/www.sh
cp -f /tmp/config/wwwrun.sh /usr/bin/wwwrun
chmod +x /usr/bin/wwwrun
chown root:root /usr/bin/wwwrun

## Server Login Script
cp /tmp/config/profile.server /home/server/.profile
chown server:server /home/server/.profile
chmod +x /home/server/.profile

## Server Login Script
cp /tmp/config/git.config /home/server/.gitconfig
chown server:server /home/server/.gitconfig
chmod 600 /home/server/.gitconfig

## Remove Passwords
passwd -d root
passwd -d server

## SSH Configuration
cp /tmp/config/sshd_config /etc/ssh
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

## System Configuration
cp /tmp/config/sysctl.conf /etc
chmod 644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf

## Logrotate Fix for LXCs
cp /tmp/config/logrotate.service /lib/systemd/system/
chmod 644 /lib/systemd/system/logrotate.service
chown root:root /lib/systemd/system/logrotate.service

## Startup Configuration
cp /tmp/config/rc-local.service /etc/systemd/system/
chmod 644 /etc/systemd/system/rc-local.service
chown root:root /etc/systemd/system/rc-local.service
cp /tmp/config/rc.local /etc/
chmod 755 /etc/rc.local
chown root:root /etc/rc.local
systemctl enable rc-local

## Main Cron Timer
cp /tmp/config/rootcron /etc/cron.d/
chmod 644 /etc/cron.d/rootcron
chown root:root /etc/cron.d/rootcron
systemctl restart cron

## Supress Slice Log Entries
cp /tmp/config/ignore-session-slice.conf /etc/rsyslog.d/
chmod 644 /etc/rsyslog.d/ignore-session-slice.conf
chown root:root /etc/rsyslog.d/ignore-session-slice.conf
systemctl restart rsyslog

## Backup Script
cp /tmp/config/svrbackup.sh /usr/bin/
chmod 755 /usr/bin/svrbackup.sh
chown root:root /usr/bin/svrbackup.sh

## Camera Cleanup Script
cp /tmp/config/camcleanup /usr/bin/
chmod 755 /usr/bin/camcleanup
chown root:root /usr/bin/camcleanup

## Samba Configuration
cp /tmp/config/smb.conf /etc/samba
chmod 644 /etc/samba/smb.conf
chown root:root /etc/samba/smb.conf

## Bind Mounts
cp -f /tmp/config/fstab /etc/fstab
chmod 644 /etc/fstab
chown root:root /etc/fstab

## Backup Drives List
cp -f /tmp/config/drives.txt /opt/
chmod 644 /opt/drives.txt
chown root:root /opt/drives.txt

## Clean-up
systemctl daemon-reload
rm -r /tmp/config/
apt-get autoremove -y
sleep 2.5
apt-get autoclean -y
exit
