#!/bin/bash
### ONLY RUN ON THE SERVER!!
### AutoConfig - ProOS for Files Container
### by Ben Provenzano III
###

## Update Sources
apt-get --yes update

## Install Packages
apt-get install -y --no-upgrade --ignore-missing unzip wget \
 rsync curl screen scrub ethtool aptitude sudo samba sshpass \
 libdbus-1-dev libdbus-glib-1-dev bc git locales mailutils \
 neofetch apt-transport-https nmap bpytop htop

## Process Monitor Symlink
ln -sf /usr/bin/bpytop /usr/bin/pytop

## Set Locale
if [ ! -e /etc/locales.generated ]; then
  dpkg-reconfigure locales
  touch /etc/locales.generated
fi

## SSH key for root user
mkdir -p /root/.ssh
cp /tmp/config/authorized_keys /root/.ssh/
chown root:root /root/.ssh/authorized_keys
chmod 644 /root/.ssh/authorized_keys

## SSH key for server user
if [ ! -e /home/server ]; then
  echo "Creating Server Home Directory..."
  mkdir -p /home/server
  mkdir -p /home/server/.ssh
  chown -R server:server /home/server
fi
cp /tmp/config/authorized_keys.server /home/server/.ssh/authorized_keys
chmod 644 /home/server/.ssh/authorized_keys
chown server:server /home/server/.ssh/authorized_keys
touch /home/server/.hushlogin
chmod 644 /home/server/.hushlogin
chown server:server /home/server/.hushlogin

## Regions Folder
mkdir -p /mnt/ben/Documents/Regions
chown server:server /mnt/ben/Documents/Regions

## User Symlinks
if [ ! -e "/home/server/ProOS" ]; then
  echo "Linking ProOS to server home folder."	
  ln -s /mnt/ben/ProOS /home/server/ProOS
fi
if [ ! -e "/home/server/Downloads" ]; then
  echo "Linking downloads to server home folder."	
  ln -s /mnt/scratch/downloads /home/server/Downloads
fi

## Server Login Script
cp /tmp/config/profile.server /home/server/.profile
chown server:server /home/server/.profile
chmod +x /home/server/.profile

## Remove Passwords
passwd -d root
passwd -d server

## SSH Configuration
cp /tmp/config/sshd_config /etc/ssh
chmod 644 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

## System Configuration
cp /tmp/config/sysctl.conf /etc
chmod 644 /etc/sysctl.conf
chown root:root /etc/sysctl.conf

## Logrotate Fix for LXCs
cp /tmp/config/logrotate.service /lib/systemd/system/
chmod 644 /lib/systemd/system/logrotate.service
chown root:root /lib/systemd/system/logrotate.service

## Startup Configuration
cp /tmp/config/rc-local.service /etc/systemd/system/
chmod 644 /etc/systemd/system/rc-local.service
chown root:root /etc/systemd/system/rc-local.service
cp /tmp/config/rc.local /etc/
chmod 755 /etc/rc.local
chown root:root /etc/rc.local
systemctl enable rc-local

## Main Cron Timer
cp /tmp/config/rootcron /etc/cron.d/
chmod 644 /etc/cron.d/rootcron
chown root:root /etc/cron.d/rootcron
systemctl restart cron

## Suppress Slice Log Entries
cp /tmp/config/ignore-session-slice.conf /etc/rsyslog.d/
chmod 644 /etc/rsyslog.d/ignore-session-slice.conf
chown root:root /etc/rsyslog.d/ignore-session-slice.conf
systemctl restart rsyslog

## Main Menu Script
cp /tmp/config/svrutil.bin /usr/bin/
chmod 755 /usr/bin/svrutil.bin
chown root:root /usr/bin/svrutil.bin
cp /tmp/config/svrbackup.bin /usr/bin/
chmod 755 /usr/bin/svrbackup.bin
chown root:root /usr/bin/svrbackup.bin

## Camera Cleanup Script
cp /tmp/config/camcleanup /usr/bin/
chmod 755 /usr/bin/camcleanup
chown root:root /usr/bin/camcleanup

## Samba Configuration
cp /tmp/config/smb.conf /etc/samba
chmod 644 /etc/samba/smb.conf
chown root:root /etc/samba/smb.conf

## Clean-up
systemctl daemon-reload
rm -r /tmp/config/
apt-get autoremove -y
sleep 2.5
apt-get autoclean -y
exit
