#!/bin/bash
###########################################################
## GridPi main script by Ben Provenzano III v1 ############
###########################################################
###########################################################

case "$1" in

boot)
## Light Web Server
systemctl start lighttpd
## Unified Web Server
systemctl start rpi-urserver
## LED Controller
/opt/rpi/leds fc 40
sleep 4.25
/opt/rpi/leds stop
## Disable HDMI
/usr/bin/tvservice -o
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;
	    
    *)
      echo "AirGrid Server for Raspberry Pi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
