#!/bin/bash
###########################################################
## GridPi main script by Ben Provenzano III v1 ############
###########################################################
###########################################################

case "$1" in

boot)
## Light Web Server
systemctl start lighttpd
## Unified Web Server
systemctl start rpi-urserver
## LED Controller
/opt/rpi/leds fc 40
sleep 4.25
/opt/rpi/leds stop
## Disable HDMI
/usr/bin/tvservice -o
exit
;;

timer)
## This script is ran every 5-min
exit
;;

usbplug)
## This script is ran after USB drive attached
echo "no function assigned"
exit
;;

300sine)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-sine.wav'
exit
) > /dev/null 2>&1 &
;;

600sine)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-sine.wav'
) > /dev/null 2>&1 &
;;

1ksine)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-sine.wav'
exit
) > /dev/null 2>&1 &
;;

300square)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-square.wav'
exit
) > /dev/null 2>&1 &
;;

600square)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-square.wav'
exit
) > /dev/null 2>&1 &
;;

1ksquare)
(
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-square.wav'
exit
) > /dev/null 2>&1 &
;;

stop)
(
## Stop audio player
killall -s KILL -w mpv
exit
) > /dev/null 2>&1 &
;;

skip)
(
## Skip to next video
killall omxplayer.bin 
exit
) > /dev/null 2>&1 &
;;
	    
    *)
      echo "AirGrid Server for Raspberry Pi"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
