#!/bin/bash
###########################################################
## LEDwall main script by Ben Provenzano III v7 ###########
###########################################################
###########################################################

case "$1" in

boot)
## WiFi Toggle Switch
systemctl start rpi-wifiswitch
## LED Controller
/opt/rpi/leds fc norm
## Flash LED
/usr/bin/python3 - <<END
import time
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 12
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, True)
time.sleep(0.5)
GPIO.output(GPIO_PIN, False)
GPIO.cleanup()
quit()
END
exit
;;

apdled-on)
## Turn WiFi LED On
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 26
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, True)
quit()
END
exit
;;

apdled-off)
## Turn WiFi LED Off
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 26
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, False)
GPIO.cleanup()
quit()
END
exit
;;

whtledon)
## White Front LED On
touch /tmp/whtled.save
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 12
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, True)
quit()
END
exit
;;

whtledoff)
## White Front LED Off
rm -f /tmp/whtled.save
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 12
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, False)
GPIO.cleanup()
quit()
END
exit
;;

whtled)
## White Front LED Toggle
if [ -e /tmp/whtled.save ]; then
rm -f /tmp/whtled.save
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 12
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, False)
GPIO.cleanup()
quit()
END
else
/usr/bin/python3 - <<END
import RPi.GPIO as GPIO
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO_PIN = 12
GPIO.setup(GPIO_PIN, GPIO.OUT)
GPIO.output(GPIO_PIN, True)
quit()
END
fi
exit
;;

	    
    *)
        if [ "$1" == "" ]; then
          echo "Enter valid command."
        else  
	      if [ "$2" == "" ]; then
	        echo "Sending $1 command..."
	      else
	      	echo "Sending $1:$2 command..."
	      fi  
	      /opt/rpi/leds "$1" "$2" 
	    fi
      exit
     ;;
    esac
