#!/bin/bash
###########################################################
## HiFi mini main script by Ben Provenzano III ############
###########################################################
###########################################################

## Read the 2nd Argument
ARG2=$2

case "$1" in

boot)
## Light Web Server
systemctl start lighttpd
## Startup Sound
/usr/bin/amixer set PCM 50%
/usr/bin/aplay /opt/rpi/sounds/ps2.wav
## Set Volume
/usr/bin/amixer set PCM 95%
## AirPlay Support
systemctl start rpi-airplay
## Attach Server Shares / Relax Sound Loop
if ping -c 1 10.177.1.4 > /dev/null 2> /dev/null
then
  systemctl start autofs
  systemctl set-environment rpi_relaxmode=boot
  systemctl start rpi-relaxloop
else
  echo "server not found."  
fi
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Disable Activity LED
echo none | tee /sys/class/leds/led0/trigger
## Auto Hotspot (on boot only)
systemctl start rpi-netdetect
exit
;;

relax)
## Play sound in loop
systemctl stop rpi-relaxloop
systemctl set-environment rpi_relaxmode=$ARG2
systemctl start rpi-relaxloop
exit
;;

stoprelax)
systemctl stop rpi-relaxloop
exit
;;

vup)
## Volume Up
/usr/bin/amixer set PCM 2%+
exit
;;

vdwn)
## Volume Down
/usr/bin/amixer set PCM 2%-
exit
;;

300sine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-sine.wav'
exit
;;

600sine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-sine.wav'
;;

1ksine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-sine.wav'
exit
;;

300square)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-square.wav'
exit
;;

600square)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-square.wav'
exit
;;

1ksquare)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-square.wav'
exit
;;

stop)
## Stop audio player
killall -s KILL -w mpv
exit
;;

skip)
## Skip to next video
killall omxplayer.bin 
exit
;;
	    
    *)
      echo "HiFi mini"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
