#!/bin/bash
###########################################################
## HiFi mini main script by Ben Provenzano III ############
###########################################################
###########################################################

## Auto Relax Sound
RELAX=fan

## Read the 2nd Argument
ARG2=$2

case "$1" in

boot)
## Light Web Server
systemctl start lighttpd
## Startup Sound
/usr/bin/amixer set PCM 50%
/usr/bin/aplay /opt/rpi/sounds/ps2.wav
## Set Volume
/usr/bin/amixer set PCM 95%
## AirPlay Support
systemctl start rpi-airplay
## Attach Server SMB Share
sleep 5.75
if ping -c 1 files.home > /dev/null 2> /dev/null
then
  systemctl start autofs
  ## Start Relaxation Sound Automatically
  DOW=$(date +%u)  
  HOUR=$(date +%H)
  if [ "$DOW" = "5" ] || [ "$DOW" = "6" ]; then
	echo "is Fri or Sat, hour is $HOUR"
	if (( 9 <= 10#$HOUR && 10#$HOUR < 23 )); then 
	  echo "not between 11pm and 8am, not starting."
	else  
	  echo "starting $RELAX sound..."
	  screen -dm /opt/rpi/main relax $RELAX
	fi
  else
	echo "is Sun or weekday, hour is $HOUR"
	if (( 9 <= 10#$HOUR && 10#$HOUR < 21 )); then 
	  echo "not between 9pm and 8am, not starting."
	else  
	  echo "starting $RELAX sound..."
	  screen -dm /opt/rpi/main relax $RELAX
	fi
  fi
fi
## Disable HDMI (saves 30mA of power draw)
/opt/vc/bin/tvservice -o
## Disable Activity LED
echo none | tee /sys/class/leds/led0/trigger
## Auto Hotspot (on boot only)
sleep 60
systemctl start rpi-netdetect.service
exit
;;

### Relaxation Sound Playback
stoprelax)
killall -s KILL -w omxplayer
exit
;;
##
relax)
killall -s KILL -w omxplayer
## Capitialize first letter of argument
ARG2="${ARG2^}"
## Play Audio in Loop
/usr/bin/omxplayer -o alsa --loop "/mnt/smb/Media/Sounds/Relaxation/$ARG2.mp3"
exit
;;

vup)
## Volume Up
/usr/bin/amixer set PCM 2%+
exit
;;

vdwn)
## Volume Down
/usr/bin/amixer set PCM 2%-
exit
;;

300sine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-sine.wav'
exit
;;

600sine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-sine.wav'
;;

1ksine)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-sine.wav'
exit
;;

300square)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/300hz-square.wav'
exit
;;

600square)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/600hz-square.wav'
exit
;;

1ksquare)
killall -s KILL -w mpv
screen -dm /usr/bin/mpv --no-video --loop-file '/opt/rpi/1khz-square.wav'
exit
;;

stop)
## Stop audio player
killall -s KILL -w mpv
exit
;;

skip)
## Skip to next video
killall omxplayer.bin 
exit
;;
	    
    *)
      echo "HiFi mini"
	  echo "  by Ben Provenzano III"
	  echo " "
	  echo "Enter a valid command line argument."
      exit 1
      ;;
    esac
