#!/bin/sh
## System Configuration Script v6.0
## Bedroom Pi

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot/firmware
cp -fv $BIN/modconf/config.txt /boot/firmware/
mount -o remount,ro /boot/firmware

## Arduino configuration
/opt/rpi/arduino-cli core install arduino:avr

## Link main script
ln -sf /opt/rpi/main /usr/bin/main

exit
