#!/bin/bash
###########################################################

## Read the 2nd Argument
ARG2=$2

## Read the 1st Argument
case "$1" in

boot)
## Bluetooth Audio
systemctl start hciuart
systemctl start bluetooth
systemctl start bt-agent@hci0
systemctl start bluealsa-aplay
## File Share
systemctl start autofs
## Arduino COMs
ln -sf /dev/ttyACM0 /dev/zterm-tty
systemctl start rpi-ztermcom
exit
;;

relax)
## Pi audio input
echo "D" > /dev/zterm
## Play sound in loop
systemctl stop rpi-relaxloop
systemctl set-environment rpi_relaxmode=$ARG2
systemctl start rpi-relaxloop
exit
;;

stoprelax)
## Apple TV input
echo "C" > /dev/zterm
systemctl stop rpi-relaxloop
exit
;;

sleepmode)
## Toggle Sounds On/Off 
if (systemctl is-active --quiet rpi-relaxloop.service); then
  ## Apple TV input
  echo "C" > /dev/zterm
  echo "Stopping playback..."
  systemctl stop rpi-relaxloop
else 
  ## Pi audio input
  echo "D" > /dev/zterm	
  echo "Starting sleep mode..."
  systemctl stop rpi-relaxloop
  systemctl set-environment rpi_relaxmode="coldwar"
  systemctl start rpi-relaxloop
fi
exit
;;

toggletv)
echo "Toggling TV Power..."
echo "E" > /dev/zterm
exit
;;


	*)
	  echo "Bedroom Pi"
	  echo "by Ben Provenzano III "
	  exit 1
	;;
    esac   
