#!/bin/sh
## Bedroom Automate Configuration Script v6.0

# Import Host name
HOSTNAME=`cat /opt/rpi/config/hostname`
## Set Module Path
BIN=/opt/rpi
# Import Brand name
MODNAME=`cat $BIN/modconf/brand.txt`

if [ ! -e /opt/rpi/init ]; then
echo "Core components missing or corrupted."
echo "Exiting..."
sleep 1
exit
else
echo "Components integrity verified."
fi

echo "Starting $MODNAME configuration..."

## Copy Boot Config
mount -o remount,rw /boot
sleep 1.25
cp -r $BIN/modconf/config.txt /boot/
## Disable Auto Hotspot
touch /boot/autohotspot.off
mount -o remount,ro /boot

## Install Remotes
cp -r $BIN/modconf/remotes/* /opt/rpi/remotes/

## Enable LED remotes
ln -sf /opt/rpi/effects/remotes /opt/rpi/remotes/leds

## Stage II - Set module name to configs
if [ ! -e $BIN/modconf/brand.txt ]; then
echo "Skip module naming."
else
echo "Setting module name."
## Module specific home page
cp -f $BIN/modconf/client.html /opt/rpi/manager/
chmod 644 /opt/rpi/manager/client.html
chown root:root /opt/rpi/manager/client.html
## Set module name to unified server
sed -i "s/RaspberryPi/$MODNAME/g" /opt/rpi/manager/client.html
sed -i "s/raspberrypi/$HOSTNAME/g" /opt/rpi/manager/client.html
fi

## Homebridge Setup
HOMEBRIDGE="no"
#HOMEBRIDGE="" # uncomment to install
if [ -z "$HOMEBRIDGE" ]; then
  if [ ! -e /usr/bin/homebridge ]; then
  echo "Installing Homebridge..."
  npm install -g --unsafe-perm homebridge
  npm install -g --unsafe-perm homebridge-script2@latest
  mkdir -p /var/lib/homebridge
  mkdir -p /var/lib/homebridge/persist
  mkdir -p /var/lib/homebridge/accessories
  else
  echo "Homebridge already installed."
  cp -f $BIN/modconf/config.json /var/lib/homebridge/
  chmod 644 /var/lib/homebridge/config.json
  chown root:root /var/lib/homebridge/config.json
  echo "To add to Home app in iOS"
  echo "run 'systemctl stop rpi-homebridge'"
  echo "then 'homebridge -U /var/lib/homebridge -I'"
  echo "to get QR code to add bridge."
  fi
  cp -f $BIN/modconf/rpi-homebridge.service /etc/systemd/system/
  chmod -f 644 /etc/systemd/system/rpi-homebridge.service
  chown -f root:root /etc/systemd/system/rpi-homebridge.service
  systemctl disable rpi-homebridge
else
  rm -f /opt/rpi/hbapi
  rm -f /usr/bin/homebridge
  rm -rf /var/lib/homebridge
  rm -f /etc/systemd/system/rpi-homebridge.service
fi 

## ALSA Configuration
cp -f $BIN/modconf/asound.conf /etc/
chmod 644 /etc/asound.conf
chown root:root /etc/asound.conf

## AutoFS Configuration
cp -f $BIN/modconf/auto.master /etc/
chmod 644 /etc/auto.master
chown root:root /etc/auto.master
cp -f $BIN/modconf/auto.map /etc/
chmod 644 /etc/auto.map
chown root:root /etc/auto.map
mkdir -p /mnt/smb

## Link RPi to global commands library
ln -sf /opt/rpi/main /usr/bin/main
ln -sf /opt/rpi/main-rf /usr/bin/main-rf
ln -sf /opt/rpi/xmit /usr/bin/xmit

## Change Web Server Default Theme
/opt/rpi/init dblue

exit
