#!/bin/bash

## Command Aliases
alias matrix='/usr/bin/cmatrix'
alias login="/mnt/ProOS/login.sh"
alias logon="/mnt/ProOS/login.sh"

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# Set text colors
ambertty=`tput setaf 3`
bluetty=`tput setaf 4`
resettty=`tput sgr0`

uname -m -n -s -o -r
echo "${ambertty}"
echo "  _____            ____   _____ "
echo " |  __ \          / __ \ / ____|"
echo " | |__) | __ ___ | |  | | (___  "
echo " |  ___/ '__/ _ \| |  | |\___ \ "
echo " | |   | | | (_) | |__| |____) |"
echo " |_|   |_|  \___/ \____/|_____/ "
echo "${bluetty}"
echo "by Ben Provenzano III"
echo "${resettty}"

alias less='less --RAW-CONTROL-CHARS'
export LS_OPTS='--color=auto'
alias ls='ls ${LS_OPTS}'

cd /mnt/ProOS